/**
 * UniJob — Firestore Seed Script (Enhanced v3)
 * Run: node scripts/seed.mjs
 *
 * Seeds: users (25), jobs (80), applications (40+), ratings (24+),
 *        jobCompletions (10), workHistory (10)
 */

import { initializeApp } from 'firebase/app';
import {
  getFirestore,
  collection,
  doc,
  setDoc,
  addDoc,
  Timestamp,
} from 'firebase/firestore';
import { readFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

// ── Load Firebase config from .env.local ─────────────────────────────────────
const __dirname = dirname(fileURLToPath(import.meta.url));
const envFile = readFileSync(resolve(__dirname, '../.env.local'), 'utf8');
const env = Object.fromEntries(
  envFile
    .split('\n')
    .filter((l) => l && !l.startsWith('#') && l.includes('='))
    .map((l) => [l.slice(0, l.indexOf('=')).trim(), l.slice(l.indexOf('=') + 1).trim()])
);

const firebaseConfig = {
  apiKey: env.VITE_FIREBASE_API_KEY,
  authDomain: env.VITE_FIREBASE_AUTH_DOMAIN,
  projectId: env.VITE_FIREBASE_PROJECT_ID,
  storageBucket: env.VITE_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: env.VITE_FIREBASE_MESSAGING_SENDER_ID,
  appId: env.VITE_FIREBASE_APP_ID,
  measurementId: env.VITE_FIREBASE_MEASUREMENT_ID,
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

// ── Helpers ──────────────────────────────────────────────────────────────────
const daysFromNow = (n) => Timestamp.fromDate(new Date(Date.now() + n * 86_400_000));
const daysAgo = (n) => Timestamp.fromDate(new Date(Date.now() - n * 86_400_000));
const hoursFromNow = (n) => Timestamp.fromDate(new Date(Date.now() + n * 3_600_000));

// ══════════════════════════════════════════════════════════════════════════════
// 1. USERS  (15 users — original 6 + 9 new)
// ══════════════════════════════════════════════════════════════════════════════
const USERS = [
  {
    uid: 'seed-user-001',
    email: 'nguyen.van.an@hcmut.edu.vn',
    displayName: 'Nguyễn Văn An',
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=an',
    faculty: 'Khoa học & Kỹ thuật Máy tính',
    department: 'Kỹ thuật Phần mềm',
    studentId: '2213456',
    phone: '0901234567',
    bio: 'Sinh viên năm 3 KHMT, đam mê lập trình và AI. Intern tại FPT Software.',
    skills: ['React', 'Python', 'Node.js', 'Firebase', 'TypeScript', 'Docker'],
    ratingScore: 4.8,
    totalRatings: 12,
    activeJobCount: 1,
    maxJobLimit: 5,
    isAnonymous: false,
  },
  {
    uid: 'seed-user-002',
    email: 'tran.thi.bich@hcmut.edu.vn',
    displayName: 'Trần Thị Bích',
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=bich',
    faculty: 'Điện - Điện tử',
    department: 'Hệ thống nhúng',
    studentId: '2213789',
    phone: '0912345678',
    bio: 'Yêu thích thiết kế mạch và lập trình nhúng. Giải nhì IoT Hackathon BK 2025.',
    skills: ['Arduino', 'MATLAB', 'C/C++', 'PCB Design', 'STM32', 'IoT'],
    ratingScore: 4.5,
    totalRatings: 8,
    activeJobCount: 0,
    maxJobLimit: 5,
    isAnonymous: false,
  },
  {
    uid: 'seed-user-003',
    email: 'le.quoc.cuong@hcmut.edu.vn',
    displayName: 'Lê Quốc Cường',
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=cuong',
    faculty: 'Cơ khí',
    department: 'Thiết kế Máy',
    studentId: '2114001',
    phone: '0923456789',
    bio: 'Thành thạo AutoCAD và SolidWorks, có kinh nghiệm thực tập tại Bosch Việt Nam.',
    skills: ['AutoCAD', 'SolidWorks', 'Ansys', 'Thiết kế 3D', 'CNC Programming'],
    ratingScore: 4.2,
    totalRatings: 5,
    activeJobCount: 2,
    maxJobLimit: 5,
    isAnonymous: false,
  },
  {
    uid: 'seed-user-004',
    email: 'pham.ngoc.diem@hcmut.edu.vn',
    displayName: 'Phạm Ngọc Diễm',
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=diem',
    faculty: 'Quản lý Công nghiệp',
    department: 'Quản trị kinh doanh',
    studentId: '2213012',
    phone: '0934567890',
    bio: 'Thành thạo Office, kỹ năng tổ chức sự kiện tốt. Chủ tịch CLB Kinh tế BK.',
    skills: ['Excel', 'PowerPoint', 'Word', 'Tổ chức sự kiện', 'Canva', 'Marketing'],
    ratingScore: 4.9,
    totalRatings: 20,
    activeJobCount: 1,
    maxJobLimit: 5,
    isAnonymous: false,
  },
  {
    uid: 'seed-user-005',
    email: 'hoang.minh.duc@hcmut.edu.vn',
    displayName: 'Hoàng Minh Đức',
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=duc',
    faculty: 'Khoa học & Kỹ thuật Máy tính',
    department: 'Mạng máy tính',
    studentId: '2213567',
    phone: '0945678901',
    bio: 'Sinh viên năm 4, có kinh nghiệm dạy kèm Toán và Lập trình. TOEIC 920.',
    skills: ['Java', 'Spring Boot', 'SQL', 'Dạy kèm', 'Toán cao cấp', 'TOEIC'],
    ratingScore: 4.6,
    totalRatings: 15,
    activeJobCount: 0,
    maxJobLimit: 5,
    isAnonymous: false,
  },
  {
    uid: 'seed-user-006',
    email: 'nguyen.thu.huong@hcmut.edu.vn',
    displayName: 'Nguyễn Thu Hương',
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=huong',
    faculty: 'Khoa học & Kỹ thuật Máy tính',
    department: 'Trí tuệ nhân tạo',
    studentId: '2313001',
    phone: '0956789012',
    bio: 'Thiết kế đồ họa và UI/UX là đam mê. Đang thực tập tại một startup.',
    skills: ['Figma', 'Adobe Illustrator', 'Photoshop', 'UI/UX', 'Canva', 'After Effects'],
    ratingScore: 4.7,
    totalRatings: 6,
    activeJobCount: 0,
    maxJobLimit: 3,
    isAnonymous: false,
  },
  // ── NEW USERS 7-15 ──
  {
    uid: 'seed-user-007',
    email: 'vo.thanh.tung@hcmut.edu.vn',
    displayName: 'Võ Thành Tùng',
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=tung',
    faculty: 'Khoa học & Kỹ thuật Máy tính',
    department: 'Khoa học Dữ liệu',
    studentId: '2213890',
    phone: '0967890123',
    bio: 'Đam mê Data Science và Machine Learning. Top 3 Kaggle BK 2025.',
    skills: ['Python', 'TensorFlow', 'Pandas', 'SQL', 'Power BI', 'Machine Learning'],
    ratingScore: 4.4,
    totalRatings: 9,
    activeJobCount: 1,
    maxJobLimit: 5,
    isAnonymous: false,
  },
  {
    uid: 'seed-user-008',
    email: 'nguyen.thi.mai@hcmut.edu.vn',
    displayName: 'Nguyễn Thị Mai',
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mai',
    faculty: 'Kỹ thuật Hóa học',
    department: 'Hóa hữu cơ',
    studentId: '2214567',
    phone: '0978901234',
    bio: 'Sinh viên năm 3 Kỹ thuật Hóa học, giỏi tiếng Anh và dịch thuật khoa học.',
    skills: ['Hóa hữu cơ', 'Dịch thuật', 'IELTS 7.5', 'Lab Equipment', 'Research'],
    ratingScore: 4.3,
    totalRatings: 7,
    activeJobCount: 0,
    maxJobLimit: 4,
    isAnonymous: false,
  },
  {
    uid: 'seed-user-009',
    email: 'tran.quoc.bao@hcmut.edu.vn',
    displayName: 'Trần Quốc Bảo',
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=bao',
    faculty: 'Xây dựng',
    department: 'Kỹ thuật Xây dựng',
    studentId: '2115678',
    phone: '0989012345',
    bio: 'Sinh viên năm 4, đam mê AutoCAD và thiết kế kết cấu. Intern tại Coteccons.',
    skills: ['AutoCAD', 'Revit', 'SAP2000', 'Thiết kế kết cấu', 'MS Project'],
    ratingScore: 4.1,
    totalRatings: 4,
    activeJobCount: 1,
    maxJobLimit: 4,
    isAnonymous: false,
  },
  {
    uid: 'seed-user-010',
    email: 'le.hoang.phuc@hcmut.edu.vn',
    displayName: 'Lê Hoàng Phúc',
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=phuc',
    faculty: 'Điện - Điện tử',
    department: 'Điện tử viễn thông',
    studentId: '2214789',
    phone: '0990123456',
    bio: 'Quay phim, chụp ảnh, content creator. Kênh YouTube 10K subscribers review tech.',
    skills: ['Premiere Pro', 'Photography', 'Content Creation', 'YouTube', 'TikTok'],
    ratingScore: 4.8,
    totalRatings: 18,
    activeJobCount: 2,
    maxJobLimit: 5,
    isAnonymous: false,
  },
  {
    uid: 'seed-user-011',
    email: 'pham.minh.khoa@hcmut.edu.vn',
    displayName: 'Phạm Minh Khoa',
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=khoa',
    faculty: 'Khoa học & Kỹ thuật Máy tính',
    department: 'An toàn thông tin',
    studentId: '2213234',
    phone: '0901122334',
    bio: 'Chuyên gia an toàn thông tin. Chứng chỉ CompTIA Security+. CTF player.',
    skills: ['Cybersecurity', 'Linux', 'Networking', 'Python', 'Ethical Hacking', 'CTF'],
    ratingScore: 4.6,
    totalRatings: 10,
    activeJobCount: 0,
    maxJobLimit: 5,
    isAnonymous: false,
  },
  {
    uid: 'seed-user-012',
    email: 'do.thuy.linh@hcmut.edu.vn',
    displayName: 'Đỗ Thùy Linh',
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=linh',
    faculty: 'Quản lý Công nghiệp',
    department: 'Logistics',
    studentId: '2215012',
    phone: '0912233445',
    bio: 'Sinh viên Logistics năm 3, kỹ năng phân tích dữ liệu và quản lý chuỗi cung ứng.',
    skills: ['Excel nâng cao', 'VBA', 'Power BI', 'Supply Chain', 'Data Analysis'],
    ratingScore: 4.5,
    totalRatings: 11,
    activeJobCount: 1,
    maxJobLimit: 5,
    isAnonymous: false,
  },
  {
    uid: 'seed-user-013',
    email: 'nguyen.duc.huy@hcmut.edu.vn',
    displayName: 'Nguyễn Đức Huy',
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=huy',
    faculty: 'Khoa học Ứng dụng',
    department: 'Vật lý Kỹ thuật',
    studentId: '2316001',
    phone: '0923344556',
    bio: 'Sinh viên năm 2, thích dạy kèm Vật lý và Toán. GPA 3.8/4.0.',
    skills: ['Vật lý đại cương', 'Toán cao cấp', 'LaTeX', 'MATLAB', 'Dạy kèm'],
    ratingScore: 4.9,
    totalRatings: 22,
    activeJobCount: 2,
    maxJobLimit: 5,
    isAnonymous: false,
  },
  {
    uid: 'seed-user-014',
    email: 'bui.ngoc.han@hcmut.edu.vn',
    displayName: 'Bùi Ngọc Hân',
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=han',
    faculty: 'Môi trường & Tài nguyên',
    department: 'Kỹ thuật Môi trường',
    studentId: '2215234',
    phone: '0934455667',
    bio: 'Quan tâm đến phát triển bền vững. Tình nguyện viên môi trường tích cực.',
    skills: ['GIS', 'Environmental Science', 'Excel', 'Tình nguyện', 'Photoshop'],
    ratingScore: 4.0,
    totalRatings: 3,
    activeJobCount: 0,
    maxJobLimit: 3,
    isAnonymous: false,
  },
  {
    uid: 'seed-user-015',
    email: 'ly.thanh.dat@hcmut.edu.vn',
    displayName: 'Lý Thanh Đạt',
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=dat',
    faculty: 'Khoa học & Kỹ thuật Máy tính',
    department: 'Hệ thống thông tin',
    studentId: '2213678',
    phone: '0945566778',
    bio: 'Full-stack developer, đam mê web và mobile. Freelancer Fiverr 50+ orders.',
    skills: ['React', 'React Native', 'Node.js', 'MongoDB', 'Firebase', 'Tailwind CSS'],
    ratingScore: 4.7,
    totalRatings: 14,
    activeJobCount: 1,
    maxJobLimit: 5,
    isAnonymous: false,
  },
  // ── NEW USERS 16-25 ──
  {
    uid: 'seed-user-016',
    email: 'tran.ngoc.anh@hcmut.edu.vn',
    displayName: 'Trần Ngọc Ánh',
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=anh16',
    faculty: 'Quản lý Công nghiệp',
    department: 'Marketing',
    studentId: '2315001',
    phone: '0901111222',
    bio: 'Sinh viên Marketing năm 3, thành thạo Digital Marketing và content writing.',
    skills: ['Content Writing', 'SEO', 'Facebook Ads', 'Canva', 'Google Analytics'],
    ratingScore: 4.3,
    totalRatings: 6,
    activeJobCount: 1,
    maxJobLimit: 4,
    isAnonymous: false,
  },
  {
    uid: 'seed-user-017',
    email: 'nguyen.van.binh@hcmut.edu.vn',
    displayName: 'Nguyễn Văn Bình',
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=binh17',
    faculty: 'Kỹ thuật Giao thông',
    department: 'Kỹ thuật Ô tô',
    studentId: '2115890',
    phone: '0912222333',
    bio: 'Sinh viên Kỹ thuật Ô tô năm 4, thành thạo AutoCAD và thiết kế cơ khí ô tô.',
    skills: ['AutoCAD', 'SolidWorks', 'CATIA', 'Cơ khí ô tô', 'Matlab'],
    ratingScore: 3.9,
    totalRatings: 4,
    activeJobCount: 0,
    maxJobLimit: 3,
    isAnonymous: false,
  },
  {
    uid: 'seed-user-018',
    email: 'le.thi.cam@hcmut.edu.vn',
    displayName: 'Lê Thị Cẩm',
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=cam18',
    faculty: 'Khoa học Ứng dụng',
    department: 'Toán ứng dụng',
    studentId: '2316234',
    phone: '0923333444',
    bio: 'Yêu toán và thống kê. Dạy kèm Toán A1/A2 đã 2 năm, phương pháp dễ hiểu.',
    skills: ['Toán cao cấp', 'Thống kê', 'R', 'SPSS', 'Dạy kèm', 'LaTeX'],
    ratingScore: 4.8,
    totalRatings: 25,
    activeJobCount: 2,
    maxJobLimit: 5,
    isAnonymous: false,
  },
  {
    uid: 'seed-user-019',
    email: 'pham.thanh.long@hcmut.edu.vn',
    displayName: 'Phạm Thanh Long',
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=long19',
    faculty: 'Khoa học & Kỹ thuật Máy tính',
    department: 'Kỹ thuật Phần mềm',
    studentId: '2213999',
    phone: '0934444555',
    bio: 'Backend developer chuyên Java Spring Boot, đam mê microservices và DevOps.',
    skills: ['Java', 'Spring Boot', 'Docker', 'Kubernetes', 'PostgreSQL', 'Redis'],
    ratingScore: 4.5,
    totalRatings: 8,
    activeJobCount: 1,
    maxJobLimit: 5,
    isAnonymous: false,
  },
  {
    uid: 'seed-user-020',
    email: 'hoang.thi.dung@hcmut.edu.vn',
    displayName: 'Hoàng Thị Dung',
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=dung20',
    faculty: 'Điện - Điện tử',
    department: 'Kỹ thuật Điện',
    studentId: '2214890',
    phone: '0945555666',
    bio: 'Sinh viên Kỹ thuật Điện năm 3, thành thạo vẽ bản vẽ điện và PLC.',
    skills: ['AutoCAD Electrical', 'PLC', 'SCADA', 'Thiết kế điện', 'MATLAB Simulink'],
    ratingScore: 4.2,
    totalRatings: 5,
    activeJobCount: 0,
    maxJobLimit: 4,
    isAnonymous: false,
  },
  {
    uid: 'seed-user-021',
    email: 'vu.quoc.hung@hcmut.edu.vn',
    displayName: 'Vũ Quốc Hùng',
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=hung21',
    faculty: 'Xây dựng',
    department: 'Kỹ thuật Công trình',
    studentId: '2116001',
    phone: '0956666777',
    bio: 'Năm 4 Xây dựng, thành thạo Revit BIM và giám sát công trình.',
    skills: ['Revit', 'AutoCAD', 'BIM', 'Etabs', 'Quản lý công trình', 'MS Project'],
    ratingScore: 4.0,
    totalRatings: 3,
    activeJobCount: 1,
    maxJobLimit: 3,
    isAnonymous: false,
  },
  {
    uid: 'seed-user-022',
    email: 'nguyen.bich.ngoc@hcmut.edu.vn',
    displayName: 'Nguyễn Bích Ngọc',
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ngoc22',
    faculty: 'Môi trường & Tài nguyên',
    department: 'Quản lý Môi trường',
    studentId: '2215678',
    phone: '0967777888',
    bio: 'Đam mê môi trường và phát triển bền vững. Kỹ năng viết báo cáo và thuyết trình tốt.',
    skills: ['GIS', 'ArcGIS', 'Báo cáo môi trường', 'Excel', 'Word', 'Tình nguyện'],
    ratingScore: 4.1,
    totalRatings: 4,
    activeJobCount: 0,
    maxJobLimit: 3,
    isAnonymous: false,
  },
  {
    uid: 'seed-user-023',
    email: 'tran.minh.quan@hcmut.edu.vn',
    displayName: 'Trần Minh Quân',
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=quan23',
    faculty: 'Khoa học & Kỹ thuật Máy tính',
    department: 'Trí tuệ nhân tạo',
    studentId: '2314001',
    phone: '0978888999',
    bio: 'Sinh viên AI năm 2, đam mê Computer Vision và Deep Learning. Có GPU RTX 3060.',
    skills: ['Python', 'PyTorch', 'Computer Vision', 'OpenCV', 'Deep Learning', 'YOLO'],
    ratingScore: 4.6,
    totalRatings: 7,
    activeJobCount: 1,
    maxJobLimit: 4,
    isAnonymous: false,
  },
  {
    uid: 'seed-user-024',
    email: 'do.thanh.son@hcmut.edu.vn',
    displayName: 'Đỗ Thanh Sơn',
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=son24',
    faculty: 'Cơ khí',
    department: 'Kỹ thuật Nhiệt',
    studentId: '2116345',
    phone: '0989999000',
    bio: 'Năm 4 Cơ khí, giỏi MATLAB và Simulink. Có kinh nghiệm gia sư Vật lý, Nhiệt động lực học.',
    skills: ['MATLAB', 'Simulink', 'Nhiệt động lực học', 'Cơ học lưu chất', 'Dạy kèm'],
    ratingScore: 4.4,
    totalRatings: 9,
    activeJobCount: 0,
    maxJobLimit: 5,
    isAnonymous: false,
  },
  {
    uid: 'seed-user-025',
    email: 'le.ngoc.tram@hcmut.edu.vn',
    displayName: 'Lê Ngọc Trâm',
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=tram25',
    faculty: 'Quản lý Công nghiệp',
    department: 'Kế toán tài chính',
    studentId: '2215890',
    phone: '0900011222',
    bio: 'Sinh viên Kế toán năm 3, thành thạo Excel, VBA kế toán và phần mềm MISA.',
    skills: ['Excel nâng cao', 'VBA', 'MISA', 'Kế toán', 'Tài chính doanh nghiệp', 'QuickBooks'],
    ratingScore: 4.7,
    totalRatings: 13,
    activeJobCount: 1,
    maxJobLimit: 5,
    isAnonymous: false,
  },
];

// ══════════════════════════════════════════════════════════════════════════════
// 2. JOBS  (30 jobs: 14 open, 4 urgent, 6 in-progress, 6 completed)
// ══════════════════════════════════════════════════════════════════════════════
const JOBS = [
  // ────────────────── OPEN JOBS (14) ──────────────────
  {
    title: 'Gia sư Giải tích 1 cho sinh viên năm nhất',
    description:
      'Cần tìm gia sư dạy kèm môn Giải tích 1 (MA1001) cho sinh viên năm nhất. Học 2 buổi/tuần, mỗi buổi 1.5 tiếng. Học trực tiếp tại BK hoặc online đều được.',
    category: 'tutoring',
    faculty: 'Khoa học & Kỹ thuật Máy tính',
    isUrgent: false,
    isAnonymous: false,
    payment: 150000,
    paymentType: 'hourly',
    duration: '3 giờ/tuần',
    deadline: daysFromNow(14),
    maxApplicants: 3,
    status: 'open',
    postedBy: 'seed-user-006',
    postedByName: 'Nguyễn Thu Hương',
    postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=huong',
    assignedTo: [],
    applicants: [],
    tags: ['giải tích', 'toán', 'năm nhất', 'gia sư', 'online'],
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    title: 'Nhập liệu Excel cho báo cáo nghiên cứu',
    description:
      'Cần người nhập liệu từ file PDF sang Excel, khoảng 500 dòng dữ liệu thống kê. Yêu cầu chính xác và cẩn thận. Có thể làm tại nhà.',
    category: 'data-entry',
    faculty: 'Quản lý Công nghiệp',
    isUrgent: false,
    isAnonymous: false,
    payment: 200000,
    paymentType: 'fixed',
    duration: '1–2 ngày',
    deadline: daysFromNow(5),
    maxApplicants: 2,
    status: 'open',
    postedBy: 'seed-user-003',
    postedByName: 'Lê Quốc Cường',
    postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=cuong',
    assignedTo: [],
    applicants: [],
    tags: ['excel', 'nhập liệu', 'thống kê', 'làm tại nhà'],
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    title: 'Thiết kế poster sự kiện CLB Robotics',
    description:
      'CLB Robotics BK cần thiết kế 1 poster A3 và 1 banner online cho buổi workshop "Lập trình Robot cùng Arduino". Cần có file gốc (AI/PSD).',
    category: 'design',
    faculty: 'Điện - Điện tử',
    isUrgent: true,
    isAnonymous: false,
    payment: 300000,
    paymentType: 'fixed',
    duration: '2 ngày',
    deadline: daysFromNow(3),
    maxApplicants: 3,
    status: 'open',
    postedBy: 'seed-user-002',
    postedByName: 'Trần Thị Bích',
    postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=bich',
    assignedTo: [],
    applicants: [],
    tags: ['thiết kế', 'poster', 'CLB', 'robotics', 'khẩn cấp'],
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    title: 'Dịch tài liệu kỹ thuật Anh-Việt (8 trang)',
    description:
      'Cần dịch 8 trang tài liệu kỹ thuật từ tiếng Anh sang tiếng Việt về chủ đề mạch điện tử. Yêu cầu am hiểu thuật ngữ kỹ thuật.',
    category: 'translation',
    faculty: 'Điện - Điện tử',
    isUrgent: false,
    isAnonymous: false,
    payment: 250000,
    paymentType: 'fixed',
    duration: '3 ngày',
    deadline: daysFromNow(7),
    maxApplicants: 2,
    status: 'open',
    postedBy: 'seed-user-002',
    postedByName: 'Trần Thị Bích',
    postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=bich',
    assignedTo: [],
    applicants: [],
    tags: ['dịch thuật', 'tiếng anh', 'kỹ thuật', 'điện tử'],
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    title: 'Hỗ trợ nghiên cứu: thu thập dữ liệu khảo sát',
    description:
      'Cần sinh viên hỗ trợ thu thập dữ liệu khảo sát về thói quen học tập của sinh viên BK. Phát và thu bảng hỏi tại các khoa, nhập liệu Google Forms. ~200 phiếu.',
    category: 'research',
    faculty: 'Khoa học Ứng dụng',
    isUrgent: false,
    isAnonymous: false,
    payment: 400000,
    paymentType: 'fixed',
    duration: '1 tuần',
    deadline: daysFromNow(10),
    maxApplicants: 2,
    status: 'open',
    postedBy: 'seed-user-005',
    postedByName: 'Hoàng Minh Đức',
    postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=duc',
    assignedTo: [],
    applicants: [],
    tags: ['nghiên cứu', 'khảo sát', 'thu thập dữ liệu', 'google forms'],
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
  },
  {
    title: 'Trực văn phòng CLB Kỹ thuật (cuối tuần)',
    description:
      'Cần người trực văn phòng CLB vào thứ 7 và CN (8h–12h). Nhiệm vụ: tiếp nhận đơn đăng ký, trả lời email, sắp xếp tài liệu.',
    category: 'office',
    faculty: 'Khác',
    isUrgent: false,
    isAnonymous: false,
    payment: 100000,
    paymentType: 'hourly',
    duration: '8 giờ/tuần',
    deadline: daysFromNow(20),
    maxApplicants: 1,
    status: 'open',
    postedBy: 'seed-user-004',
    postedByName: 'Phạm Ngọc Diễm',
    postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=diem',
    assignedTo: [],
    applicants: [],
    tags: ['văn phòng', 'cuối tuần', 'hành chính', 'CLB'],
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    title: 'Tình nguyện hỗ trợ Ngày hội Tuyển sinh BK 2026',
    description:
      'Cần 10 tình nguyện viên hỗ trợ Ngày hội Tuyển sinh ngày 20/4/2026. Nhiệm vụ: hướng dẫn thí sinh, phát tài liệu, hỗ trợ đăng ký. Được cấp áo, bữa trưa, giấy chứng nhận.',
    category: 'volunteer',
    faculty: 'Khác',
    isUrgent: false,
    isAnonymous: false,
    payment: 0,
    paymentType: 'volunteer',
    duration: '1 ngày (8h–17h)',
    deadline: daysFromNow(19),
    maxApplicants: 10,
    status: 'open',
    postedBy: 'seed-user-004',
    postedByName: 'Phạm Ngọc Diễm',
    postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=diem',
    assignedTo: [],
    applicants: [],
    tags: ['tình nguyện', 'tuyển sinh', 'hướng dẫn', 'sự kiện'],
    createdAt: daysAgo(6),
    updatedAt: daysAgo(6),
  },
  {
    title: 'Gia sư Lập trình C++ cơ bản',
    description:
      'Cần gia sư dạy kèm C++ (CO1027) cho sinh viên CS năm 1-2. Dạy online qua Zoom, 3 buổi/tuần. Ưu tiên người có thành tích tốt.',
    category: 'tutoring',
    faculty: 'Khoa học & Kỹ thuật Máy tính',
    isUrgent: false,
    isAnonymous: false,
    payment: 120000,
    paymentType: 'hourly',
    duration: '4.5 giờ/tuần',
    deadline: daysFromNow(12),
    maxApplicants: 2,
    status: 'open',
    postedBy: 'seed-user-006',
    postedByName: 'Nguyễn Thu Hương',
    postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=huong',
    assignedTo: [],
    applicants: [],
    tags: ['C++', 'lập trình', 'gia sư', 'CO1027', 'online'],
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    title: 'Phân tích dữ liệu bán hàng bằng Python',
    description:
      'Cần sinh viên có kinh nghiệm Python/Pandas phân tích dataset bán hàng ~10K records. Output: file Jupyter Notebook với biểu đồ và insights.',
    category: 'data-entry',
    faculty: 'Khoa học & Kỹ thuật Máy tính',
    isUrgent: false,
    isAnonymous: false,
    payment: 500000,
    paymentType: 'fixed',
    duration: '3-4 ngày',
    deadline: daysFromNow(8),
    maxApplicants: 2,
    status: 'open',
    postedBy: 'seed-user-012',
    postedByName: 'Đỗ Thùy Linh',
    postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=linh',
    assignedTo: [],
    applicants: [],
    tags: ['python', 'data analysis', 'pandas', 'jupyter', 'visualization'],
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    title: 'Thiết kế UI/UX cho app di động (Figma)',
    description:
      'Cần designer thiết kế UI/UX cho ứng dụng quản lý thời gian dành cho sinh viên. Bao gồm: 8-10 màn hình chính, wireframe + high-fidelity mockup.',
    category: 'design',
    faculty: 'Khoa học & Kỹ thuật Máy tính',
    isUrgent: false,
    isAnonymous: false,
    payment: 800000,
    paymentType: 'fixed',
    duration: '1 tuần',
    deadline: daysFromNow(14),
    maxApplicants: 3,
    status: 'open',
    postedBy: 'seed-user-015',
    postedByName: 'Lý Thanh Đạt',
    postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=dat',
    assignedTo: [],
    applicants: [],
    tags: ['figma', 'UI/UX', 'mobile app', 'design', 'wireframe'],
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    title: 'Viết bài SEO cho blog công nghệ (5 bài)',
    description:
      'Cần content writer viết 5 bài blog về công nghệ (AI, Cloud, DevOps), mỗi bài 800-1200 từ. Cần tối ưu SEO, có keyword research.',
    category: 'other',
    faculty: 'Khác',
    isUrgent: false,
    isAnonymous: true,
    payment: 200000,
    paymentType: 'fixed',
    duration: '5-7 ngày',
    deadline: daysFromNow(10),
    maxApplicants: 3,
    status: 'open',
    postedBy: 'seed-user-011',
    postedByName: 'Phạm Minh Khoa',
    postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=khoa',
    assignedTo: [],
    applicants: [],
    tags: ['content writing', 'SEO', 'blog', 'công nghệ', 'ẩn danh'],
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    title: 'Tạo dashboard Power BI từ dữ liệu khảo sát',
    description:
      'Cần tạo interactive dashboard trên Power BI từ file Excel ~2000 dòng dữ liệu khảo sát sức khỏe sinh viên.',
    category: 'data-entry',
    faculty: 'Quản lý Công nghiệp',
    isUrgent: false,
    isAnonymous: false,
    payment: 600000,
    paymentType: 'fixed',
    duration: '4-5 ngày',
    deadline: daysFromNow(12),
    maxApplicants: 2,
    status: 'open',
    postedBy: 'seed-user-004',
    postedByName: 'Phạm Ngọc Diễm',
    postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=diem',
    assignedTo: [],
    applicants: [],
    tags: ['power bi', 'dashboard', 'data visualization', 'excel'],
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
  },
  {
    title: 'Chụp ảnh sản phẩm cho shop online (50 sản phẩm)',
    description:
      'Cần photographer chụp ảnh sản phẩm handmade (trang sức) cho shop online. 50 sản phẩm, mỗi sản phẩm 3-5 góc. Phông nền trắng.',
    category: 'other',
    faculty: 'Khác',
    isUrgent: false,
    isAnonymous: false,
    payment: 700000,
    paymentType: 'fixed',
    duration: '2-3 ngày',
    deadline: daysFromNow(7),
    maxApplicants: 2,
    status: 'open',
    postedBy: 'seed-user-014',
    postedByName: 'Bùi Ngọc Hân',
    postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=han',
    assignedTo: [],
    applicants: [],
    tags: ['chụp ảnh', 'photography', 'product', 'shop online'],
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    title: 'Gia sư môn Xác suất Thống kê cho nhóm 3 người',
    description:
      'Nhóm 3 bạn sinh viên năm 2 cần gia sư dạy kèm Xác suất Thống kê (MT2013). Học 2 buổi/tuần, 2 tiếng/buổi. Ưu tiên dạy offline tại thư viện BK.',
    category: 'tutoring',
    faculty: 'Khoa học Ứng dụng',
    isUrgent: false,
    isAnonymous: false,
    payment: 200000,
    paymentType: 'hourly',
    duration: '4 giờ/tuần',
    deadline: daysFromNow(21),
    maxApplicants: 3,
    status: 'open',
    postedBy: 'seed-user-009',
    postedByName: 'Trần Quốc Bảo',
    postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=bao',
    assignedTo: [],
    applicants: [],
    tags: ['gia sư', 'xác suất', 'thống kê', 'nhóm', 'offline'],
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },

  // ────────────────── URGENT JOBS (4) ──────────────────
  {
    title: 'Cần gấp: Sửa bug website ReactJS trước thuyết trình',
    description:
      'Website đồ án cuối kỳ bị lỗi routing và CSS responsive. Cần fix gấp trong 3 giờ, thuyết trình sáng mai 8h. Sẵn sàng trả cao. Repo GitHub có sẵn.',
    category: 'other',
    faculty: 'Khoa học & Kỹ thuật Máy tính',
    isUrgent: true,
    isAnonymous: false,
    payment: 400000,
    paymentType: 'fixed',
    duration: '2-3 giờ',
    deadline: hoursFromNow(12),
    maxApplicants: 1,
    status: 'open',
    postedBy: 'seed-user-009',
    postedByName: 'Trần Quốc Bảo',
    postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=bao',
    assignedTo: [],
    applicants: [],
    tags: ['ReactJS', 'bug fix', 'urgent', 'khẩn cấp', 'frontend'],
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },
  {
    title: 'Cần gấp: Quay video sự kiện Hackathon tối nay',
    description:
      'CLB BKIT cần cameraman quay video cho sự kiện Hackathon diễn ra tối nay 18h-22h tại hội trường A4. Cần có thiết bị quay phim cá nhân.',
    category: 'other',
    faculty: 'Khoa học & Kỹ thuật Máy tính',
    isUrgent: true,
    isAnonymous: false,
    payment: 500000,
    paymentType: 'fixed',
    duration: '4 giờ',
    deadline: hoursFromNow(6),
    maxApplicants: 2,
    status: 'open',
    postedBy: 'seed-user-011',
    postedByName: 'Phạm Minh Khoa',
    postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=khoa',
    assignedTo: [],
    applicants: [],
    tags: ['quay video', 'cameraman', 'hackathon', 'sự kiện', 'khẩn cấp'],
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },
  {
    title: 'Cần gấp: Thay trực phòng lab chiều nay',
    description:
      'Mình bị ốm đột xuất, cần người thay trực phòng lab Điện tử từ 13h-17h hôm nay. Chỉ cần ngồi trực, cho sinh viên mượn/trả thiết bị.',
    category: 'office',
    faculty: 'Điện - Điện tử',
    isUrgent: true,
    isAnonymous: false,
    payment: 150000,
    paymentType: 'fixed',
    duration: '4 giờ',
    deadline: hoursFromNow(4),
    maxApplicants: 1,
    status: 'open',
    postedBy: 'seed-user-002',
    postedByName: 'Trần Thị Bích',
    postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=bich',
    assignedTo: [],
    applicants: [],
    tags: ['trực lab', 'thay ca', 'khẩn cấp', 'điện tử'],
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },
  {
    title: 'Cần gấp: In 200 trang tài liệu + đóng bìa',
    description:
      'Cần người giúp in ấn 200 trang tài liệu (đã có file PDF), đóng bìa cứng 5 cuốn. Cần xong trong 2 giờ. Đã có tiệm in quen.',
    category: 'other',
    faculty: 'Khác',
    isUrgent: true,
    isAnonymous: true,
    payment: 100000,
    paymentType: 'fixed',
    duration: '2 giờ',
    deadline: hoursFromNow(3),
    maxApplicants: 1,
    status: 'open',
    postedBy: 'seed-user-013',
    postedByName: 'Nguyễn Đức Huy',
    postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=huy',
    assignedTo: [],
    applicants: [],
    tags: ['in ấn', 'đóng bìa', 'gấp', 'khẩn cấp', 'ẩn danh'],
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },

  // ────────────────── IN-PROGRESS JOBS (6) ──────────────────
  {
    title: 'Nhập liệu danh sách thiết bị phòng thí nghiệm',
    description:
      'Nhập liệu danh sách ~300 thiết bị thí nghiệm vào Google Sheets từ bản in. Cần điền đầy đủ: tên, mã, số lượng, tình trạng.',
    category: 'data-entry',
    faculty: 'Cơ khí',
    isUrgent: false,
    isAnonymous: false,
    payment: 180000,
    paymentType: 'fixed',
    duration: '2 ngày',
    deadline: daysFromNow(2),
    maxApplicants: 1,
    status: 'in-progress',
    postedBy: 'seed-user-003',
    postedByName: 'Lê Quốc Cường',
    postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=cuong',
    assignedTo: ['seed-user-001'],
    applicants: ['seed-user-001'],
    tags: ['nhập liệu', 'google sheets', 'thiết bị', 'phòng lab'],
    createdAt: daysAgo(5),
    updatedAt: daysAgo(1),
  },
  {
    title: 'Hỗ trợ trợ giảng môn Vật lý đại cương',
    description:
      'Cần trợ giảng hỗ trợ chấm bài và giải đáp thắc mắc cho sinh viên trong giờ thực hành Vật lý đại cương. 2 buổi/tuần.',
    category: 'teaching-assistant',
    faculty: 'Khoa học Ứng dụng',
    isUrgent: false,
    isAnonymous: false,
    payment: 130000,
    paymentType: 'hourly',
    duration: '6 giờ/tuần',
    deadline: daysFromNow(30),
    maxApplicants: 2,
    status: 'in-progress',
    postedBy: 'seed-user-005',
    postedByName: 'Hoàng Minh Đức',
    postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=duc',
    assignedTo: ['seed-user-013'],
    applicants: ['seed-user-013', 'seed-user-006'],
    tags: ['trợ giảng', 'vật lý', 'chấm bài', 'teaching assistant'],
    createdAt: daysAgo(10),
    updatedAt: daysAgo(3),
  },
  {
    title: 'Code landing page cho dự án startup',
    description:
      'Code 1 landing page responsive bằng ReactJS + Tailwind CSS cho dự án startup EduTech. Có thiết kế Figma sẵn.',
    category: 'other',
    faculty: 'Khoa học & Kỹ thuật Máy tính',
    isUrgent: false,
    isAnonymous: false,
    payment: 800000,
    paymentType: 'fixed',
    duration: '4-5 ngày',
    deadline: daysFromNow(5),
    maxApplicants: 2,
    status: 'in-progress',
    postedBy: 'seed-user-011',
    postedByName: 'Phạm Minh Khoa',
    postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=khoa',
    assignedTo: ['seed-user-015'],
    applicants: ['seed-user-015', 'seed-user-001'],
    tags: ['ReactJS', 'Tailwind', 'landing page', 'frontend', 'responsive'],
    createdAt: daysAgo(7),
    updatedAt: daysAgo(2),
  },
  {
    title: 'Dạy kèm IELTS Writing Task 2 (3 buổi)',
    description:
      'Cần tutor IELTS Writing, đặc biệt Task 2. 3 buổi online qua Google Meet, mỗi buổi 90 phút.',
    category: 'tutoring',
    faculty: 'Khác',
    isUrgent: false,
    isAnonymous: false,
    payment: 180000,
    paymentType: 'hourly',
    duration: '4.5 giờ',
    deadline: daysFromNow(14),
    maxApplicants: 2,
    status: 'in-progress',
    postedBy: 'seed-user-009',
    postedByName: 'Trần Quốc Bảo',
    postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=bao',
    assignedTo: ['seed-user-008'],
    applicants: ['seed-user-008', 'seed-user-005'],
    tags: ['IELTS', 'writing', 'dạy kèm', 'tiếng anh', 'online'],
    createdAt: daysAgo(8),
    updatedAt: daysAgo(2),
  },
  {
    title: 'Xây dựng mô hình 3D chi tiết máy bằng SolidWorks',
    description:
      'Cần vẽ mô hình 3D cho 5 chi tiết máy (trục, bánh răng, ổ lăn, nắp ổ, gối đỡ). Có bản vẽ 2D, cần chuyển sang 3D + render.',
    category: 'other',
    faculty: 'Cơ khí',
    isUrgent: false,
    isAnonymous: false,
    payment: 450000,
    paymentType: 'fixed',
    duration: '5 ngày',
    deadline: daysFromNow(7),
    maxApplicants: 1,
    status: 'in-progress',
    postedBy: 'seed-user-009',
    postedByName: 'Trần Quốc Bảo',
    postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=bao',
    assignedTo: ['seed-user-003'],
    applicants: ['seed-user-003'],
    tags: ['SolidWorks', '3D modeling', 'cơ khí', 'chi tiết máy'],
    createdAt: daysAgo(6),
    updatedAt: daysAgo(1),
  },
  {
    title: 'Thiết kế bộ nhận diện thương hiệu CLB Sách BK',
    description:
      'Cần thiết kế: logo, banner Facebook/Instagram, template poster sự kiện, name card cho CLB Sách BK.',
    category: 'design',
    faculty: 'Khác',
    isUrgent: false,
    isAnonymous: false,
    payment: 1000000,
    paymentType: 'fixed',
    duration: '2 tuần',
    deadline: daysFromNow(14),
    maxApplicants: 2,
    status: 'in-progress',
    postedBy: 'seed-user-012',
    postedByName: 'Đỗ Thùy Linh',
    postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=linh',
    assignedTo: ['seed-user-006'],
    applicants: ['seed-user-006', 'seed-user-010'],
    tags: ['branding', 'logo', 'design', 'CLB', 'nhận diện'],
    createdAt: daysAgo(10),
    updatedAt: daysAgo(3),
  },

  // ────────────────── COMPLETED JOBS (6) ──────────────────
  {
    title: 'Thiết kế slide thuyết trình đồ án tốt nghiệp',
    description:
      'Cần thiết kế 20 slide PowerPoint cho đồ án tốt nghiệp ngành CNTT. Cung cấp nội dung, yêu cầu bố cục chuyên nghiệp.',
    category: 'design',
    faculty: 'Khoa học & Kỹ thuật Máy tính',
    isUrgent: false,
    isAnonymous: false,
    payment: 350000,
    paymentType: 'fixed',
    duration: '3 ngày',
    deadline: daysAgo(2),
    maxApplicants: 2,
    status: 'completed',
    postedBy: 'seed-user-001',
    postedByName: 'Nguyễn Văn An',
    postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=an',
    assignedTo: ['seed-user-006'],
    applicants: ['seed-user-006', 'seed-user-004'],
    tags: ['thiết kế', 'powerpoint', 'slide', 'đồ án'],
    createdAt: daysAgo(14),
    updatedAt: daysAgo(2),
  },
  {
    title: 'Dịch abstract luận văn sang tiếng Anh',
    description:
      'Cần dịch phần abstract (khoảng 300 từ) của luận văn thạc sĩ sang tiếng Anh học thuật.',
    category: 'translation',
    faculty: 'Quản lý Công nghiệp',
    isUrgent: false,
    isAnonymous: false,
    payment: 150000,
    paymentType: 'fixed',
    duration: '1 ngày',
    deadline: daysAgo(5),
    maxApplicants: 1,
    status: 'completed',
    postedBy: 'seed-user-003',
    postedByName: 'Lê Quốc Cường',
    postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=cuong',
    assignedTo: ['seed-user-005'],
    applicants: ['seed-user-005'],
    tags: ['dịch thuật', 'tiếng anh', 'abstract', 'luận văn'],
    createdAt: daysAgo(20),
    updatedAt: daysAgo(5),
  },
  {
    title: 'Tạo website portfolio cá nhân bằng HTML/CSS',
    description:
      'Cần tạo website portfolio 1 page responsive. Sections: About, Skills, Projects, Contact.',
    category: 'other',
    faculty: 'Khoa học & Kỹ thuật Máy tính',
    isUrgent: false,
    isAnonymous: false,
    payment: 350000,
    paymentType: 'fixed',
    duration: '3 ngày',
    deadline: daysAgo(7),
    maxApplicants: 2,
    status: 'completed',
    postedBy: 'seed-user-008',
    postedByName: 'Nguyễn Thị Mai',
    postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mai',
    assignedTo: ['seed-user-015'],
    applicants: ['seed-user-015', 'seed-user-001'],
    tags: ['HTML', 'CSS', 'portfolio', 'responsive', 'web development'],
    createdAt: daysAgo(18),
    updatedAt: daysAgo(7),
  },
  {
    title: 'Chạy mô phỏng Ansys cho bài tập Cơ học kết cấu',
    description:
      'Cần người có kinh nghiệm Ansys chạy mô phỏng FEA cho 3 bài toán cơ học kết cấu.',
    category: 'research',
    faculty: 'Xây dựng',
    isUrgent: false,
    isAnonymous: false,
    payment: 500000,
    paymentType: 'fixed',
    duration: '4 ngày',
    deadline: daysAgo(3),
    maxApplicants: 1,
    status: 'completed',
    postedBy: 'seed-user-009',
    postedByName: 'Trần Quốc Bảo',
    postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=bao',
    assignedTo: ['seed-user-003'],
    applicants: ['seed-user-003'],
    tags: ['Ansys', 'FEA', 'cơ học', 'mô phỏng', 'kết cấu'],
    createdAt: daysAgo(15),
    updatedAt: daysAgo(3),
  },
  {
    title: 'Phân tích dữ liệu khảo sát sức khỏe tinh thần SV',
    description:
      'Phân tích dataset 500 records từ khảo sát sức khỏe tinh thần sinh viên BK. Dùng SPSS hoặc Python.',
    category: 'research',
    faculty: 'Khoa học Ứng dụng',
    isUrgent: false,
    isAnonymous: false,
    payment: 450000,
    paymentType: 'fixed',
    duration: '5 ngày',
    deadline: daysAgo(10),
    maxApplicants: 2,
    status: 'completed',
    postedBy: 'seed-user-013',
    postedByName: 'Nguyễn Đức Huy',
    postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=huy',
    assignedTo: ['seed-user-007'],
    applicants: ['seed-user-007', 'seed-user-012'],
    tags: ['data analysis', 'SPSS', 'statistics', 'khảo sát', 'sức khỏe'],
    createdAt: daysAgo(25),
    updatedAt: daysAgo(10),
  },
  {
    title: 'Quay và dựng video giới thiệu CLB Truyền thông BK',
    description:
      'Quay video 3 phút giới thiệu CLB Truyền thông BK. Bao gồm phỏng vấn 3 thành viên, B-roll hoạt động.',
    category: 'other',
    faculty: 'Khác',
    isUrgent: false,
    isAnonymous: false,
    payment: 600000,
    paymentType: 'fixed',
    duration: '5 ngày',
    deadline: daysAgo(4),
    maxApplicants: 2,
    status: 'completed',
    postedBy: 'seed-user-004',
    postedByName: 'Phạm Ngọc Diễm',
    postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=diem',
    assignedTo: ['seed-user-010'],
    applicants: ['seed-user-010'],
    tags: ['video production', 'quay phim', 'dựng phim', 'CLB', 'truyền thông'],
    createdAt: daysAgo(16),
    updatedAt: daysAgo(4),
  },

  // ══════════════ EXTRA 50 JOBS (v3) ══════════════

  // ── OPEN: Tutoring (8) ──
  {
    title: 'Gia sư Vật lý đại cương nhóm 2 người',
    description: 'Cần gia sư dạy kèm Vật lý đại cương (PH1003) cho 2 sinh viên năm 1. Học trực tiếp tại BK, 2 buổi/tuần. Ưu tiên sinh viên Khoa học Ứng dụng hoặc Cơ khí.',
    category: 'tutoring', faculty: 'Khoa học Ứng dụng', isUrgent: false, isAnonymous: false,
    payment: 130000, paymentType: 'hourly', duration: '4 giờ/tuần', deadline: daysFromNow(10),
    maxApplicants: 2, status: 'open',
    postedBy: 'seed-user-016', postedByName: 'Trần Ngọc Ánh', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=anh16',
    assignedTo: [], applicants: [], tags: ['vật lý', 'gia sư', 'năm nhất', 'nhóm'],
    createdAt: daysAgo(1), updatedAt: daysAgo(1),
  },
  {
    title: 'Dạy kèm Hóa học đại cương cho sinh viên năm 1',
    description: 'Cần người dạy kèm Hóa học đại cương (CH1003). Yêu cầu giải bài tập, giảng lý thuyết rõ ràng. Online qua Zoom 3 buổi/tuần.',
    category: 'tutoring', faculty: 'Kỹ thuật Hóa học', isUrgent: false, isAnonymous: false,
    payment: 120000, paymentType: 'hourly', duration: '4.5 giờ/tuần', deadline: daysFromNow(12),
    maxApplicants: 2, status: 'open',
    postedBy: 'seed-user-022', postedByName: 'Nguyễn Bích Ngọc', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ngoc22',
    assignedTo: [], applicants: [], tags: ['hóa học', 'gia sư', 'năm nhất', 'online'],
    createdAt: daysAgo(2), updatedAt: daysAgo(2),
  },
  {
    title: 'Gia sư môn Lập trình hướng đối tượng (OOP)',
    description: 'Cần gia sư dạy kèm CO2003 - OOP cho sinh viên năm 2. Ưu tiên sinh viên KHMT đã qua môn với điểm A. Dạy online Zoom.',
    category: 'tutoring', faculty: 'Khoa học & Kỹ thuật Máy tính', isUrgent: false, isAnonymous: false,
    payment: 140000, paymentType: 'hourly', duration: '3 giờ/tuần', deadline: daysFromNow(18),
    maxApplicants: 2, status: 'open',
    postedBy: 'seed-user-020', postedByName: 'Hoàng Thị Dung', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=dung20',
    assignedTo: [], applicants: [], tags: ['OOP', 'Java', 'lập trình', 'gia sư', 'CO2003'],
    createdAt: daysAgo(3), updatedAt: daysAgo(3),
  },
  {
    title: 'Gia sư môn Kinh tế vi mô cho sinh viên Quản lý',
    description: 'Cần gia sư môn Kinh tế vi mô (EM1002) cho sinh viên Quản lý Công nghiệp năm 1. Học tại thư viện BK hoặc Zoom.',
    category: 'tutoring', faculty: 'Quản lý Công nghiệp', isUrgent: false, isAnonymous: false,
    payment: 110000, paymentType: 'hourly', duration: '2 giờ/tuần', deadline: daysFromNow(15),
    maxApplicants: 1, status: 'open',
    postedBy: 'seed-user-017', postedByName: 'Nguyễn Văn Bình', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=binh17',
    assignedTo: [], applicants: [], tags: ['kinh tế', 'gia sư', 'quản lý', 'EM1002'],
    createdAt: daysAgo(4), updatedAt: daysAgo(4),
  },
  {
    title: 'Dạy kèm môn Cơ học kỹ thuật (Tĩnh học)',
    description: 'Cần gia sư dạy Tĩnh học (ME1002) cho sinh viên Cơ khí năm 2. Tập trung vào giải bài tập và phương pháp giải nhanh.',
    category: 'tutoring', faculty: 'Cơ khí', isUrgent: false, isAnonymous: false,
    payment: 125000, paymentType: 'hourly', duration: '3 giờ/tuần', deadline: daysFromNow(10),
    maxApplicants: 2, status: 'open',
    postedBy: 'seed-user-021', postedByName: 'Vũ Quốc Hùng', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=hung21',
    assignedTo: [], applicants: [], tags: ['cơ học', 'tĩnh học', 'gia sư', 'cơ khí'],
    createdAt: daysAgo(1), updatedAt: daysAgo(1),
  },
  {
    title: 'Gia sư luyện thi IELTS Writing Task 2',
    description: 'Cần gia sư IELTS chuyên Writing Task 2, target 7.0+. Học 2 buổi/tuần, sửa bài và feedback chi tiết. Online Zoom.',
    category: 'tutoring', faculty: 'Khác', isUrgent: false, isAnonymous: false,
    payment: 200000, paymentType: 'hourly', duration: '4 giờ/tuần', deadline: daysFromNow(21),
    maxApplicants: 1, status: 'open',
    postedBy: 'seed-user-019', postedByName: 'Phạm Thanh Long', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=long19',
    assignedTo: [], applicants: [], tags: ['IELTS', 'tiếng anh', 'writing', 'gia sư'],
    createdAt: daysAgo(2), updatedAt: daysAgo(2),
  },
  {
    title: 'Dạy kèm Toán rời rạc cho SV KHMT',
    description: 'Cần gia sư môn Toán rời rạc (MT2013) cho sinh viên KHMT năm 2. Tập trung chương đồ thị và đệ quy. Online hoặc trực tiếp.',
    category: 'tutoring', faculty: 'Khoa học & Kỹ thuật Máy tính', isUrgent: false, isAnonymous: false,
    payment: 135000, paymentType: 'hourly', duration: '3 giờ/tuần', deadline: daysFromNow(14),
    maxApplicants: 2, status: 'open',
    postedBy: 'seed-user-025', postedByName: 'Lê Ngọc Trâm', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=tram25',
    assignedTo: [], applicants: [], tags: ['toán rời rạc', 'MT2013', 'gia sư', 'KHMT'],
    createdAt: daysAgo(3), updatedAt: daysAgo(3),
  },
  {
    title: 'Gia sư môn Nhiệt động lực học cho nhóm Cơ khí',
    description: 'Nhóm 4 người cần gia sư Nhiệt động lực học (ME2007). Học trực tiếp tại BK, cuối tuần. Ưu tiên anh/chị năm 4 Cơ khí.',
    category: 'tutoring', faculty: 'Cơ khí', isUrgent: false, isAnonymous: false,
    payment: 150000, paymentType: 'hourly', duration: '4 giờ/tuần', deadline: daysFromNow(8),
    maxApplicants: 2, status: 'open',
    postedBy: 'seed-user-024', postedByName: 'Đỗ Thanh Sơn', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=son24',
    assignedTo: [], applicants: [], tags: ['nhiệt động', 'gia sư', 'cơ khí', 'nhóm', 'ME2007'],
    createdAt: daysAgo(2), updatedAt: daysAgo(2),
  },

  // ── OPEN: Data Entry (5) ──
  {
    title: 'Nhập liệu danh sách alumni cho hệ thống CRM',
    description: 'Nhập thông tin ~600 cựu sinh viên từ file Excel cũ vào hệ thống CRM (Google Sheets template có sẵn). Yêu cầu cẩn thận, chính xác.',
    category: 'data-entry', faculty: 'Quản lý Công nghiệp', isUrgent: false, isAnonymous: false,
    payment: 250000, paymentType: 'fixed', duration: '2–3 ngày', deadline: daysFromNow(6),
    maxApplicants: 2, status: 'open',
    postedBy: 'seed-user-004', postedByName: 'Phạm Ngọc Diễm', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=diem',
    assignedTo: [], applicants: [], tags: ['nhập liệu', 'CRM', 'excel', 'alumni'],
    createdAt: daysAgo(2), updatedAt: daysAgo(2),
  },
  {
    title: 'Số hóa tài liệu thư viện (đánh máy 30 trang)',
    description: 'Đánh máy 30 trang tài liệu kỹ thuật cũ từ bản in sang Word. Cần chính xác từng ký tự, bao gồm công thức toán.',
    category: 'data-entry', faculty: 'Khác', isUrgent: false, isAnonymous: false,
    payment: 180000, paymentType: 'fixed', duration: '2 ngày', deadline: daysFromNow(4),
    maxApplicants: 1, status: 'open',
    postedBy: 'seed-user-023', postedByName: 'Trần Minh Quân', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=quan23',
    assignedTo: [], applicants: [], tags: ['đánh máy', 'số hóa', 'tài liệu', 'word'],
    createdAt: daysAgo(1), updatedAt: daysAgo(1),
  },
  {
    title: 'Điền form khảo sát nghiên cứu thị trường (200 mẫu)',
    description: 'Cần người hỗ trợ phát và thu về 200 phiếu khảo sát giấy tại các điểm trong BK, sau đó nhập vào Google Forms.',
    category: 'data-entry', faculty: 'Quản lý Công nghiệp', isUrgent: false, isAnonymous: false,
    payment: 300000, paymentType: 'fixed', duration: '3 ngày', deadline: daysFromNow(7),
    maxApplicants: 2, status: 'open',
    postedBy: 'seed-user-016', postedByName: 'Trần Ngọc Ánh', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=anh16',
    assignedTo: [], applicants: [], tags: ['khảo sát', 'nhập liệu', 'thị trường', 'google forms'],
    createdAt: daysAgo(3), updatedAt: daysAgo(3),
  },
  {
    title: 'Nhập và phân loại dữ liệu sensor IoT vào database',
    description: 'Xử lý và nhập 10.000 dòng dữ liệu cảm biến từ CSV vào bảng PostgreSQL. Cần biết SQL cơ bản.',
    category: 'data-entry', faculty: 'Điện - Điện tử', isUrgent: false, isAnonymous: false,
    payment: 350000, paymentType: 'fixed', duration: '2 ngày', deadline: daysFromNow(5),
    maxApplicants: 1, status: 'open',
    postedBy: 'seed-user-002', postedByName: 'Trần Thị Bích', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=bich',
    assignedTo: [], applicants: [], tags: ['sql', 'database', 'IoT', 'csv', 'nhập liệu'],
    createdAt: daysAgo(1), updatedAt: daysAgo(1),
  },
  {
    title: 'Tổng hợp báo cáo tài chính từ 12 chi nhánh CLB',
    description: 'Tổng hợp số liệu thu chi từ 12 file Excel riêng lẻ vào 1 file báo cáo tổng hợp theo mẫu cho sẵn. Biết Excel là đủ.',
    category: 'data-entry', faculty: 'Quản lý Công nghiệp', isUrgent: false, isAnonymous: false,
    payment: 200000, paymentType: 'fixed', duration: '1 ngày', deadline: daysFromNow(3),
    maxApplicants: 1, status: 'open',
    postedBy: 'seed-user-025', postedByName: 'Lê Ngọc Trâm', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=tram25',
    assignedTo: [], applicants: [], tags: ['excel', 'kế toán', 'tổng hợp', 'báo cáo'],
    createdAt: daysAgo(2), updatedAt: daysAgo(2),
  },

  // ── OPEN: Design (6) ──
  {
    title: 'Thiết kế logo và bộ nhận diện thương hiệu cho startup',
    description: 'Startup công nghệ giáo dục cần thiết kế logo + bộ nhận diện (màu sắc, font, card visit). Cung cấp brief chi tiết. Bàn giao file AI.',
    category: 'design', faculty: 'Khác', isUrgent: false, isAnonymous: false,
    payment: 800000, paymentType: 'fixed', duration: '5 ngày', deadline: daysFromNow(10),
    maxApplicants: 3, status: 'open',
    postedBy: 'seed-user-019', postedByName: 'Phạm Thanh Long', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=long19',
    assignedTo: [], applicants: [], tags: ['logo', 'branding', 'nhận diện', 'AI file', 'startup'],
    createdAt: daysAgo(3), updatedAt: daysAgo(3),
  },
  {
    title: 'Thiết kế infographic cho báo cáo nghiên cứu',
    description: 'Cần thiết kế 5 infographic minh họa kết quả nghiên cứu về AI trong giáo dục. Cung cấp nội dung và số liệu. Bàn giao PNG + PDF.',
    category: 'design', faculty: 'Khoa học & Kỹ thuật Máy tính', isUrgent: false, isAnonymous: false,
    payment: 400000, paymentType: 'fixed', duration: '3 ngày', deadline: daysFromNow(7),
    maxApplicants: 2, status: 'open',
    postedBy: 'seed-user-023', postedByName: 'Trần Minh Quân', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=quan23',
    assignedTo: [], applicants: [], tags: ['infographic', 'thiết kế', 'nghiên cứu', 'AI'],
    createdAt: daysAgo(2), updatedAt: daysAgo(2),
  },
  {
    title: 'Thiết kế banner và assets cho mạng xã hội CLB',
    description: 'CLB Khởi nghiệp BK cần bộ template Facebook/Instagram: banner, story, thumbnail. 10 template. File Canva hoặc PSD.',
    category: 'design', faculty: 'Quản lý Công nghiệp', isUrgent: false, isAnonymous: false,
    payment: 350000, paymentType: 'fixed', duration: '4 ngày', deadline: daysFromNow(8),
    maxApplicants: 2, status: 'open',
    postedBy: 'seed-user-004', postedByName: 'Phạm Ngọc Diễm', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=diem',
    assignedTo: [], applicants: [], tags: ['social media', 'banner', 'canva', 'CLB', 'template'],
    createdAt: daysAgo(4), updatedAt: daysAgo(4),
  },
  {
    title: 'Vẽ UML diagram cho đồ án phần mềm (10 diagram)',
    description: 'Cần vẽ 10 UML diagram (use case, sequence, class) cho hệ thống quản lý thư viện. Dùng draw.io hoặc Lucidchart.',
    category: 'design', faculty: 'Khoa học & Kỹ thuật Máy tính', isUrgent: false, isAnonymous: false,
    payment: 250000, paymentType: 'fixed', duration: '2 ngày', deadline: daysFromNow(5),
    maxApplicants: 2, status: 'open',
    postedBy: 'seed-user-001', postedByName: 'Nguyễn Văn An', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=an',
    assignedTo: [], applicants: [], tags: ['UML', 'draw.io', 'phần mềm', 'đồ án', 'diagram'],
    createdAt: daysAgo(1), updatedAt: daysAgo(1),
  },
  {
    title: 'Thiết kế UI mockup mobile app (Figma)',
    description: 'Cần thiết kế 15 màn hình UI/UX cho app quản lý nhà trọ trên Figma. Có style guide cho sẵn. Ưu tiên người có portfolio.',
    category: 'design', faculty: 'Khoa học & Kỹ thuật Máy tính', isUrgent: false, isAnonymous: false,
    payment: 600000, paymentType: 'fixed', duration: '5 ngày', deadline: daysFromNow(12),
    maxApplicants: 2, status: 'open',
    postedBy: 'seed-user-015', postedByName: 'Lý Thanh Đạt', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=dat',
    assignedTo: [], applicants: [], tags: ['figma', 'UI/UX', 'mobile app', 'mockup', 'thiết kế'],
    createdAt: daysAgo(3), updatedAt: daysAgo(3),
  },
  {
    title: 'Chỉnh sửa và retouching ảnh sự kiện (80 ảnh)',
    description: 'Cần retouching 80 ảnh sự kiện: chỉnh màu, xóa background rối, tăng sáng. Bàn giao JPG chất lượng cao trong 2 ngày.',
    category: 'design', faculty: 'Khác', isUrgent: false, isAnonymous: false,
    payment: 300000, paymentType: 'fixed', duration: '2 ngày', deadline: daysFromNow(4),
    maxApplicants: 2, status: 'open',
    postedBy: 'seed-user-022', postedByName: 'Nguyễn Bích Ngọc', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ngoc22',
    assignedTo: [], applicants: [], tags: ['photoshop', 'retouching', 'ảnh sự kiện', 'lightroom'],
    createdAt: daysAgo(2), updatedAt: daysAgo(2),
  },

  // ── OPEN: Translation (4) ──
  {
    title: 'Dịch tài liệu hóa học Nhật-Việt (15 trang)',
    description: 'Dịch 15 trang tài liệu hóa học từ tiếng Nhật sang tiếng Việt. Yêu cầu am hiểu thuật ngữ hóa học và JLPT N3+.',
    category: 'translation', faculty: 'Kỹ thuật Hóa học', isUrgent: false, isAnonymous: false,
    payment: 450000, paymentType: 'fixed', duration: '4 ngày', deadline: daysFromNow(8),
    maxApplicants: 1, status: 'open',
    postedBy: 'seed-user-008', postedByName: 'Nguyễn Thị Mai', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mai',
    assignedTo: [], applicants: [], tags: ['dịch thuật', 'tiếng nhật', 'hóa học', 'JLPT'],
    createdAt: daysAgo(2), updatedAt: daysAgo(2),
  },
  {
    title: 'Dịch và biên tập báo cáo kỹ thuật Anh-Việt (20 trang)',
    description: 'Dịch báo cáo kỹ thuật điện tử 20 trang từ tiếng Anh sang tiếng Việt, bao gồm chỉnh sửa ngữ pháp và format lại.',
    category: 'translation', faculty: 'Điện - Điện tử', isUrgent: false, isAnonymous: false,
    payment: 500000, paymentType: 'fixed', duration: '3 ngày', deadline: daysFromNow(6),
    maxApplicants: 1, status: 'open',
    postedBy: 'seed-user-020', postedByName: 'Hoàng Thị Dung', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=dung20',
    assignedTo: [], applicants: [], tags: ['dịch thuật', 'tiếng anh', 'điện tử', 'biên tập'],
    createdAt: daysAgo(1), updatedAt: daysAgo(1),
  },
  {
    title: 'Subtitles tiếng Việt cho video bài giảng tiếng Anh',
    description: 'Cần viết phụ đề tiếng Việt cho 3 video bài giảng AI (tổng ~2 tiếng). Cần thành thạo tiếng Anh kỹ thuật và biết dùng Aegisub.',
    category: 'translation', faculty: 'Khoa học & Kỹ thuật Máy tính', isUrgent: false, isAnonymous: false,
    payment: 350000, paymentType: 'fixed', duration: '3 ngày', deadline: daysFromNow(7),
    maxApplicants: 1, status: 'open',
    postedBy: 'seed-user-007', postedByName: 'Võ Thành Tùng', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=tung',
    assignedTo: [], applicants: [], tags: ['subtitles', 'phụ đề', 'tiếng anh', 'video', 'AI'],
    createdAt: daysAgo(3), updatedAt: daysAgo(3),
  },
  {
    title: 'Dịch hướng dẫn sử dụng phần mềm kỹ thuật (30 trang)',
    description: 'Dịch user manual tiếng Anh của phần mềm ETABS sang tiếng Việt, 30 trang. Cần biết về kỹ thuật xây dựng.',
    category: 'translation', faculty: 'Xây dựng', isUrgent: false, isAnonymous: false,
    payment: 600000, paymentType: 'fixed', duration: '5 ngày', deadline: daysFromNow(10),
    maxApplicants: 1, status: 'open',
    postedBy: 'seed-user-021', postedByName: 'Vũ Quốc Hùng', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=hung21',
    assignedTo: [], applicants: [], tags: ['dịch thuật', 'ETABS', 'xây dựng', 'manual'],
    createdAt: daysAgo(2), updatedAt: daysAgo(2),
  },

  // ── OPEN: Research (4) ──
  {
    title: 'Hỗ trợ nghiên cứu: phân tích dữ liệu Python',
    description: 'Cần SV hỗ trợ phân tích dataset môi trường ~50.000 dòng bằng Python (Pandas/Matplotlib). Biết statistical test là lợi thế.',
    category: 'research', faculty: 'Môi trường & Tài nguyên', isUrgent: false, isAnonymous: false,
    payment: 500000, paymentType: 'fixed', duration: '1 tuần', deadline: daysFromNow(9),
    maxApplicants: 1, status: 'open',
    postedBy: 'seed-user-014', postedByName: 'Bùi Ngọc Hân', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=han',
    assignedTo: [], applicants: [], tags: ['python', 'pandas', 'nghiên cứu', 'môi trường', 'data'],
    createdAt: daysAgo(3), updatedAt: daysAgo(3),
  },
  {
    title: 'Tìm kiếm và tổng hợp tài liệu tham khảo cho luận văn',
    description: 'Cần SV hỗ trợ tìm 30 paper từ IEEE/Scopus về chủ đề Machine Learning in Healthcare, viết tóm tắt ngắn mỗi paper.',
    category: 'research', faculty: 'Khoa học & Kỹ thuật Máy tính', isUrgent: false, isAnonymous: false,
    payment: 350000, paymentType: 'fixed', duration: '3 ngày', deadline: daysFromNow(6),
    maxApplicants: 1, status: 'open',
    postedBy: 'seed-user-023', postedByName: 'Trần Minh Quân', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=quan23',
    assignedTo: [], applicants: [], tags: ['literature review', 'ML', 'research', 'IEEE', 'luận văn'],
    createdAt: daysAgo(2), updatedAt: daysAgo(2),
  },
  {
    title: 'Hỗ trợ thí nghiệm đo đạc tại phòng lab Vật lý',
    description: 'Cần 2 SV hỗ trợ chạy thí nghiệm đo đạc tính chất quang học tại phòng lab. Làm buổi chiều thứ 3 và thứ 5 trong 2 tuần.',
    category: 'research', faculty: 'Khoa học Ứng dụng', isUrgent: false, isAnonymous: false,
    payment: 100000, paymentType: 'hourly', duration: '8 giờ/tuần, 2 tuần', deadline: daysFromNow(15),
    maxApplicants: 2, status: 'open',
    postedBy: 'seed-user-024', postedByName: 'Đỗ Thanh Sơn', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=son24',
    assignedTo: [], applicants: [], tags: ['thí nghiệm', 'lab', 'vật lý', 'quang học', 'đo đạc'],
    createdAt: daysAgo(4), updatedAt: daysAgo(4),
  },
  {
    title: 'Coding hỗ trợ nghiên cứu: xây dựng crawler thu thập data',
    description: 'Cần SV KHMT hỗ trợ viết web scraper Python thu thập tin tuyển dụng từ 5 trang web. Yêu cầu biết BeautifulSoup hoặc Scrapy.',
    category: 'research', faculty: 'Khoa học & Kỹ thuật Máy tính', isUrgent: false, isAnonymous: false,
    payment: 450000, paymentType: 'fixed', duration: '3 ngày', deadline: daysFromNow(7),
    maxApplicants: 1, status: 'open',
    postedBy: 'seed-user-007', postedByName: 'Võ Thành Tùng', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=tung',
    assignedTo: [], applicants: [], tags: ['python', 'web scraping', 'crawler', 'data collection', 'nghiên cứu'],
    createdAt: daysAgo(2), updatedAt: daysAgo(2),
  },

  // ── OPEN: Event & Office (4) ──
  {
    title: 'Hỗ trợ tổ chức Workshop AI for Students (50 người)',
    description: 'Cần 3 tình nguyện viên hỗ trợ tổ chức workshop 1 ngày: check-in, phát tài liệu, điều phối phòng, chụp ảnh sự kiện.',
    category: 'event', faculty: 'Khoa học & Kỹ thuật Máy tính', isUrgent: false, isAnonymous: false,
    payment: 150000, paymentType: 'fixed', duration: '1 ngày', deadline: daysFromNow(13),
    maxApplicants: 3, status: 'open',
    postedBy: 'seed-user-011', postedByName: 'Phạm Minh Khoa', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=khoa',
    assignedTo: [], applicants: [], tags: ['sự kiện', 'workshop', 'AI', 'tình nguyện viên'],
    createdAt: daysAgo(5), updatedAt: daysAgo(5),
  },
  {
    title: 'Trực booth triển lãm khoa học tại Hội trường A',
    description: 'Cần 2 SV trực booth giới thiệu sản phẩm nghiên cứu tại triển lãm HCMUT Science Fair. Mỗi ca 4 tiếng, 2 ca/ngày trong 2 ngày.',
    category: 'event', faculty: 'Khác', isUrgent: false, isAnonymous: false,
    payment: 120000, paymentType: 'hourly', duration: '8 giờ', deadline: daysFromNow(11),
    maxApplicants: 4, status: 'open',
    postedBy: 'seed-user-018', postedByName: 'Lê Thị Cẩm', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=cam18',
    assignedTo: [], applicants: [], tags: ['sự kiện', 'triển lãm', 'booth', 'khoa học'],
    createdAt: daysAgo(3), updatedAt: daysAgo(3),
  },
  {
    title: 'Hỗ trợ văn phòng Hội Sinh viên (thứ 2-6, buổi sáng)',
    description: 'Cần 1 SV hỗ trợ văn phòng Hội Sinh viên: soạn thảo văn bản, nhập liệu danh sách, đóng dấu, trả lời email. 9h-12h từ thứ 2 đến thứ 6.',
    category: 'office', faculty: 'Khác', isUrgent: false, isAnonymous: false,
    payment: 80000, paymentType: 'hourly', duration: '15 giờ/tuần', deadline: daysFromNow(25),
    maxApplicants: 1, status: 'open',
    postedBy: 'seed-user-004', postedByName: 'Phạm Ngọc Diễm', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=diem',
    assignedTo: [], applicants: [], tags: ['văn phòng', 'hành chính', 'Hội sinh viên', 'part-time'],
    createdAt: daysAgo(6), updatedAt: daysAgo(6),
  },
  {
    title: 'Tình nguyện dọn dẹp và sắp xếp lại kho tài liệu CLB',
    description: 'CLB Kỹ thuật cần 5 tình nguyện viên phân loại và sắp xếp lại kho tài liệu, thiết bị. Thứ 7 tuần này, 8h-13h.',
    category: 'volunteer', faculty: 'Khác', isUrgent: false, isAnonymous: false,
    payment: 0, paymentType: 'volunteer', duration: '5 giờ', deadline: daysFromNow(5),
    maxApplicants: 5, status: 'open',
    postedBy: 'seed-user-003', postedByName: 'Lê Quốc Cường', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=cuong',
    assignedTo: [], applicants: [], tags: ['tình nguyện', 'dọn dẹp', 'CLB', 'kỹ thuật'],
    createdAt: daysAgo(1), updatedAt: daysAgo(1),
  },

  // ── OPEN: Tech/Other (5) ──
  {
    title: 'Xây dựng REST API Node.js cho app quản lý ký túc xá',
    description: 'Cần SV viết REST API với Node.js/Express + MongoDB cho hệ thống quản lý ký túc xá: CRUD phòng, đặt phòng, thanh toán. Có ERD sẵn.',
    category: 'other', faculty: 'Khoa học & Kỹ thuật Máy tính', isUrgent: false, isAnonymous: false,
    payment: 1200000, paymentType: 'fixed', duration: '1 tuần', deadline: daysFromNow(10),
    maxApplicants: 1, status: 'open',
    postedBy: 'seed-user-019', postedByName: 'Phạm Thanh Long', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=long19',
    assignedTo: [], applicants: [], tags: ['nodejs', 'express', 'mongodb', 'REST API', 'backend'],
    createdAt: daysAgo(2), updatedAt: daysAgo(2),
  },
  {
    title: 'Viết script Python tự động hóa báo cáo hàng tuần',
    description: 'Cần viết script Python đọc dữ liệu từ Google Sheets, tính toán KPI và tự động gửi email báo cáo HTML mỗi thứ 2. Biết Python và Google API.',
    category: 'other', faculty: 'Quản lý Công nghiệp', isUrgent: false, isAnonymous: false,
    payment: 500000, paymentType: 'fixed', duration: '3 ngày', deadline: daysFromNow(7),
    maxApplicants: 1, status: 'open',
    postedBy: 'seed-user-025', postedByName: 'Lê Ngọc Trâm', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=tram25',
    assignedTo: [], applicants: [], tags: ['python', 'automation', 'google sheets', 'email', 'script'],
    createdAt: daysAgo(3), updatedAt: daysAgo(3),
  },
  {
    title: 'Hướng dẫn setup Linux server và deploy website',
    description: 'Cần người hướng dẫn (2-3 buổi) cách setup Ubuntu server, cài Nginx, deploy ứng dụng Node.js và config SSL. Yêu cầu Linux expert.',
    category: 'teaching-assistant', faculty: 'Khoa học & Kỹ thuật Máy tính', isUrgent: false, isAnonymous: false,
    payment: 300000, paymentType: 'hourly', duration: '6 giờ (2-3 buổi)', deadline: daysFromNow(12),
    maxApplicants: 1, status: 'open',
    postedBy: 'seed-user-001', postedByName: 'Nguyễn Văn An', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=an',
    assignedTo: [], applicants: [], tags: ['linux', 'nginx', 'deploy', 'devops', 'server'],
    createdAt: daysAgo(1), updatedAt: daysAgo(1),
  },
  {
    title: 'Viết content blog kỹ thuật cho fanpage CLB AI',
    description: 'Cần viết 4 bài blog tiếng Việt về AI/ML cho fanpage CLB: dễ hiểu, có code snippet minh họa, ~800 từ/bài. Nộp Markdown.',
    category: 'other', faculty: 'Khoa học & Kỹ thuật Máy tính', isUrgent: false, isAnonymous: false,
    payment: 200000, paymentType: 'fixed', duration: '4 ngày', deadline: daysFromNow(8),
    maxApplicants: 2, status: 'open',
    postedBy: 'seed-user-011', postedByName: 'Phạm Minh Khoa', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=khoa',
    assignedTo: [], applicants: [], tags: ['content', 'blog', 'AI', 'viết lách', 'CLB'],
    createdAt: daysAgo(2), updatedAt: daysAgo(2),
  },
  {
    title: 'Setup và cấu hình mạng LAN cho phòng lab mới',
    description: 'Cần SV IT hỗ trợ kéo dây mạng, cấu hình switch và router cho phòng lab mới 20 máy. Làm cuối tuần 1 ngày.',
    category: 'other', faculty: 'Điện - Điện tử', isUrgent: false, isAnonymous: false,
    payment: 400000, paymentType: 'fixed', duration: '1 ngày', deadline: daysFromNow(6),
    maxApplicants: 2, status: 'open',
    postedBy: 'seed-user-002', postedByName: 'Trần Thị Bích', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=bich',
    assignedTo: [], applicants: [], tags: ['mạng', 'LAN', 'networking', 'lab', 'IT support'],
    createdAt: daysAgo(3), updatedAt: daysAgo(3),
  },

  // ── URGENT OPEN (6) ──
  {
    title: 'Gấp: Fix lỗi database PostgreSQL trước 20h tối nay',
    description: 'Database PostgreSQL bị lỗi foreign key constraint sau migration. Cần sửa gấp trước 20h tối nay để demo cho khách hàng. Sẵn sàng online ngay.',
    category: 'other', faculty: 'Khoa học & Kỹ thuật Máy tính', isUrgent: true, isAnonymous: false,
    payment: 300000, paymentType: 'fixed', duration: '2 giờ', deadline: hoursFromNow(4),
    maxApplicants: 1, status: 'open',
    postedBy: 'seed-user-015', postedByName: 'Lý Thanh Đạt', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=dat',
    assignedTo: [], applicants: [], tags: ['postgresql', 'database', 'fix bug', 'khẩn cấp'],
    createdAt: daysAgo(0), updatedAt: daysAgo(0),
  },
  {
    title: 'Cần gấp: Dịch 3 trang abstract tiếng Anh trong 3 tiếng',
    description: 'Cần dịch gấp 3 trang abstract tiếng Anh kỹ thuật trong 3 tiếng. Chất lượng cao, đúng thuật ngữ chuyên ngành Điện tử. Trả tiền ngay khi nhận.',
    category: 'translation', faculty: 'Điện - Điện tử', isUrgent: true, isAnonymous: false,
    payment: 200000, paymentType: 'fixed', duration: '3 giờ', deadline: hoursFromNow(3),
    maxApplicants: 1, status: 'open',
    postedBy: 'seed-user-020', postedByName: 'Hoàng Thị Dung', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=dung20',
    assignedTo: [], applicants: [], tags: ['dịch thuật', 'tiếng anh', 'khẩn cấp', 'abstract'],
    createdAt: daysAgo(0), updatedAt: daysAgo(0),
  },
  {
    title: 'Khẩn: In và đóng quyển báo cáo nhóm (5 quyển)',
    description: 'Cần người đi in và đóng quyển 5 bộ báo cáo đồ án (80 trang/quyển) tại tiệm in gần BK. File PDF đã chuẩn. Cần trước 15h chiều nay.',
    category: 'other', faculty: 'Khác', isUrgent: true, isAnonymous: false,
    payment: 150000, paymentType: 'fixed', duration: '2 giờ', deadline: hoursFromNow(3),
    maxApplicants: 1, status: 'open',
    postedBy: 'seed-user-017', postedByName: 'Nguyễn Văn Bình', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=binh17',
    assignedTo: [], applicants: [], tags: ['in ấn', 'đóng quyển', 'báo cáo', 'khẩn cấp'],
    createdAt: daysAgo(0), updatedAt: daysAgo(0),
  },
  {
    title: 'Cần gấp: Giải bài tập lập trình Python trước nộp 22h',
    description: 'Bài tập Python: đọc file CSV, xử lý dữ liệu với Pandas, vẽ biểu đồ với Matplotlib. Deadline nộp 22h tối nay. Cần hướng dẫn và giải thích code.',
    category: 'tutoring', faculty: 'Quản lý Công nghiệp', isUrgent: true, isAnonymous: true,
    payment: 150000, paymentType: 'fixed', duration: '2 giờ', deadline: hoursFromNow(5),
    maxApplicants: 1, status: 'open',
    postedBy: 'seed-user-016', postedByName: 'Trần Ngọc Ánh', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=anh16',
    assignedTo: [], applicants: [], tags: ['python', 'pandas', 'bài tập', 'khẩn cấp', 'ẩn danh'],
    createdAt: daysAgo(0), updatedAt: daysAgo(0),
  },
  {
    title: 'Gấp: Thiết kế slide 20 trang cho thuyết trình 8h sáng mai',
    description: 'Cần thiết kế gấp 20 slide PowerPoint cho thuyết trình đồ án lúc 8h sáng mai. Cung cấp nội dung đầy đủ. Trả thêm 20% nếu xong trước 2h sáng.',
    category: 'design', faculty: 'Khoa học & Kỹ thuật Máy tính', isUrgent: true, isAnonymous: false,
    payment: 400000, paymentType: 'fixed', duration: '4 giờ', deadline: hoursFromNow(10),
    maxApplicants: 1, status: 'open',
    postedBy: 'seed-user-019', postedByName: 'Phạm Thanh Long', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=long19',
    assignedTo: [], applicants: [], tags: ['powerpoint', 'slide', 'thiết kế', 'khẩn cấp', 'đồ án'],
    createdAt: daysAgo(0), updatedAt: daysAgo(0),
  },
  {
    title: 'Cần ngay: Hỗ trợ setup livestream sự kiện CLB tối nay',
    description: 'CLB Truyền thông cần 1 người biết setup OBS Studio + kết nối YouTube livestream cho sự kiện tối nay 19h. Có laptop sẵn, cần người biết config.',
    category: 'event', faculty: 'Khác', isUrgent: true, isAnonymous: false,
    payment: 200000, paymentType: 'fixed', duration: '3 giờ', deadline: hoursFromNow(6),
    maxApplicants: 1, status: 'open',
    postedBy: 'seed-user-016', postedByName: 'Trần Ngọc Ánh', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=anh16',
    assignedTo: [], applicants: [], tags: ['livestream', 'OBS', 'YouTube', 'CLB', 'khẩn cấp'],
    createdAt: daysAgo(0), updatedAt: daysAgo(0),
  },

  // ── IN-PROGRESS (4) ──
  {
    title: 'Xây dựng dashboard Power BI phân tích doanh thu CLB',
    description: 'Xây dựng dashboard Power BI phân tích thu chi 6 tháng cho CLB Kinh tế. Dữ liệu đã có trong Excel.',
    category: 'data-entry', faculty: 'Quản lý Công nghiệp', isUrgent: false, isAnonymous: false,
    payment: 400000, paymentType: 'fixed', duration: '3 ngày', deadline: daysFromNow(2),
    maxApplicants: 1, status: 'in-progress',
    postedBy: 'seed-user-025', postedByName: 'Lê Ngọc Trâm', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=tram25',
    assignedTo: ['seed-user-012'], applicants: ['seed-user-012'],
    tags: ['power bi', 'dashboard', 'phân tích', 'kế toán'],
    createdAt: daysAgo(5), updatedAt: daysAgo(1),
  },
  {
    title: 'Viết báo cáo thực hành thí nghiệm Hóa phân tích',
    description: 'Viết báo cáo thực hành từ số liệu đo được. Cần trình bày đúng format khoa học, tính toán kết quả, kết luận.',
    category: 'other', faculty: 'Kỹ thuật Hóa học', isUrgent: false, isAnonymous: false,
    payment: 200000, paymentType: 'fixed', duration: '2 ngày', deadline: daysFromNow(1),
    maxApplicants: 1, status: 'in-progress',
    postedBy: 'seed-user-017', postedByName: 'Nguyễn Văn Bình', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=binh17',
    assignedTo: ['seed-user-008'], applicants: ['seed-user-008'],
    tags: ['báo cáo', 'hóa học', 'thí nghiệm', 'viết lách'],
    createdAt: daysAgo(4), updatedAt: daysAgo(1),
  },
  {
    title: 'Chụp ảnh chân dung cho toàn bộ ban chấp hành CLB',
    description: 'Chụp ảnh chân dung 15 thành viên BCH CLB Khởi nghiệp, ngoài trời tại BK. Chỉnh sửa cơ bản, bàn giao ảnh JPG.',
    category: 'other', faculty: 'Khác', isUrgent: false, isAnonymous: false,
    payment: 500000, paymentType: 'fixed', duration: '1 ngày', deadline: daysFromNow(2),
    maxApplicants: 1, status: 'in-progress',
    postedBy: 'seed-user-004', postedByName: 'Phạm Ngọc Diễm', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=diem',
    assignedTo: ['seed-user-010'], applicants: ['seed-user-010'],
    tags: ['chụp ảnh', 'chân dung', 'CLB', 'photography'],
    createdAt: daysAgo(3), updatedAt: daysAgo(1),
  },
  {
    title: 'Lập trình Arduino cảm biến nhiệt độ và gửi dữ liệu MQTT',
    description: 'Code Arduino đọc cảm biến DHT22, gửi lên MQTT broker mỗi 5 giây. Cần tài liệu mô tả code chi tiết.',
    category: 'other', faculty: 'Điện - Điện tử', isUrgent: false, isAnonymous: false,
    payment: 350000, paymentType: 'fixed', duration: '2 ngày', deadline: daysFromNow(3),
    maxApplicants: 1, status: 'in-progress',
    postedBy: 'seed-user-023', postedByName: 'Trần Minh Quân', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=quan23',
    assignedTo: ['seed-user-002'], applicants: ['seed-user-002'],
    tags: ['arduino', 'IoT', 'MQTT', 'cảm biến', 'nhúng'],
    createdAt: daysAgo(5), updatedAt: daysAgo(2),
  },

  // ── COMPLETED (8) ──
  {
    title: 'Viết script VBA tự động xuất báo cáo Excel',
    description: 'Viết VBA macro tự động format và xuất báo cáo từ raw data mỗi tháng.',
    category: 'other', faculty: 'Quản lý Công nghiệp', isUrgent: false, isAnonymous: false,
    payment: 400000, paymentType: 'fixed', duration: '2 ngày', deadline: daysAgo(5),
    maxApplicants: 1, status: 'completed',
    postedBy: 'seed-user-025', postedByName: 'Lê Ngọc Trâm', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=tram25',
    assignedTo: ['seed-user-012'], applicants: ['seed-user-012'],
    tags: ['VBA', 'excel', 'automation', 'macro'],
    createdAt: daysAgo(15), updatedAt: daysAgo(5),
  },
  {
    title: 'Thiết kế UI/UX app đặt lịch phòng thí nghiệm',
    description: 'Thiết kế 10 màn hình Figma cho app đặt lịch phòng thí nghiệm trường.',
    category: 'design', faculty: 'Khoa học & Kỹ thuật Máy tính', isUrgent: false, isAnonymous: false,
    payment: 500000, paymentType: 'fixed', duration: '4 ngày', deadline: daysAgo(3),
    maxApplicants: 1, status: 'completed',
    postedBy: 'seed-user-019', postedByName: 'Phạm Thanh Long', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=long19',
    assignedTo: ['seed-user-006'], applicants: ['seed-user-006'],
    tags: ['figma', 'UI/UX', 'thiết kế', 'app'],
    createdAt: daysAgo(18), updatedAt: daysAgo(3),
  },
  {
    title: 'Gia sư Nhập môn lập trình (IT1010) — 4 buổi',
    description: 'Dạy kèm 4 buổi môn IT1010 cho SV KHMT năm 1. Tập trung vào Python cơ bản và bài tập.',
    category: 'tutoring', faculty: 'Khoa học & Kỹ thuật Máy tính', isUrgent: false, isAnonymous: false,
    payment: 480000, paymentType: 'fixed', duration: '8 giờ (4 buổi)', deadline: daysAgo(2),
    maxApplicants: 1, status: 'completed',
    postedBy: 'seed-user-022', postedByName: 'Nguyễn Bích Ngọc', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ngoc22',
    assignedTo: ['seed-user-001'], applicants: ['seed-user-001'],
    tags: ['python', 'gia sư', 'IT1010', 'lập trình', 'năm nhất'],
    createdAt: daysAgo(20), updatedAt: daysAgo(2),
  },
  {
    title: 'Tạo video giới thiệu sản phẩm cho Startup (2 phút)',
    description: 'Quay và dựng video 2 phút giới thiệu app mobile của startup. Script và storyboard có sẵn.',
    category: 'other', faculty: 'Khác', isUrgent: false, isAnonymous: false,
    payment: 800000, paymentType: 'fixed', duration: '3 ngày', deadline: daysAgo(7),
    maxApplicants: 1, status: 'completed',
    postedBy: 'seed-user-015', postedByName: 'Lý Thanh Đạt', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=dat',
    assignedTo: ['seed-user-010'], applicants: ['seed-user-010'],
    tags: ['video', 'quay phim', 'dựng phim', 'startup', 'premiere'],
    createdAt: daysAgo(22), updatedAt: daysAgo(7),
  },
  {
    title: 'Viết tài liệu kỹ thuật (Technical Docs) cho REST API',
    description: 'Viết Swagger/OpenAPI docs cho 20 endpoint API. Cần biết REST API và Markdown.',
    category: 'other', faculty: 'Khoa học & Kỹ thuật Máy tính', isUrgent: false, isAnonymous: false,
    payment: 350000, paymentType: 'fixed', duration: '2 ngày', deadline: daysAgo(6),
    maxApplicants: 1, status: 'completed',
    postedBy: 'seed-user-011', postedByName: 'Phạm Minh Khoa', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=khoa',
    assignedTo: ['seed-user-001'], applicants: ['seed-user-001'],
    tags: ['swagger', 'API docs', 'markdown', 'technical writing'],
    createdAt: daysAgo(18), updatedAt: daysAgo(6),
  },
  {
    title: 'Phân tích đối thủ cạnh tranh cho báo cáo Marketing',
    description: 'Phân tích 5 đối thủ cạnh tranh trên thị trường EdTech Việt Nam. Báo cáo dạng slide PowerPoint 20 trang.',
    category: 'research', faculty: 'Quản lý Công nghiệp', isUrgent: false, isAnonymous: false,
    payment: 450000, paymentType: 'fixed', duration: '3 ngày', deadline: daysAgo(4),
    maxApplicants: 1, status: 'completed',
    postedBy: 'seed-user-016', postedByName: 'Trần Ngọc Ánh', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=anh16',
    assignedTo: ['seed-user-004'], applicants: ['seed-user-004'],
    tags: ['marketing', 'competitive analysis', 'edtech', 'nghiên cứu'],
    createdAt: daysAgo(20), updatedAt: daysAgo(4),
  },
  {
    title: 'Hướng dẫn viết báo cáo khoa học bằng LaTeX',
    description: '3 buổi hướng dẫn viết báo cáo khoa học bằng LaTeX: cấu trúc, hình vẽ, bảng, trích dẫn BibTeX.',
    category: 'teaching-assistant', faculty: 'Khoa học Ứng dụng', isUrgent: false, isAnonymous: false,
    payment: 360000, paymentType: 'fixed', duration: '6 giờ (3 buổi)', deadline: daysAgo(8),
    maxApplicants: 1, status: 'completed',
    postedBy: 'seed-user-024', postedByName: 'Đỗ Thanh Sơn', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=son24',
    assignedTo: ['seed-user-018'], applicants: ['seed-user-018'],
    tags: ['LaTeX', 'báo cáo khoa học', 'hướng dẫn', 'BibTeX'],
    createdAt: daysAgo(25), updatedAt: daysAgo(8),
  },
  {
    title: 'Dịch và localise app tiếng Anh sang tiếng Việt (500 strings)',
    description: 'Dịch và localise 500 chuỗi UI/text của ứng dụng mobile từ tiếng Anh sang tiếng Việt tự nhiên. Cần hiểu ngữ cảnh app.',
    category: 'translation', faculty: 'Khoa học & Kỹ thuật Máy tính', isUrgent: false, isAnonymous: false,
    payment: 600000, paymentType: 'fixed', duration: '3 ngày', deadline: daysAgo(10),
    maxApplicants: 1, status: 'completed',
    postedBy: 'seed-user-015', postedByName: 'Lý Thanh Đạt', postedByPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=dat',
    assignedTo: ['seed-user-008'], applicants: ['seed-user-008'],
    tags: ['dịch thuật', 'localisation', 'mobile app', 'tiếng việt'],
    createdAt: daysAgo(25), updatedAt: daysAgo(10),
  },
];

// ══════════════════════════════════════════════════════════════════════════════
// 3. APPLICATIONS  (22 applications)
// ══════════════════════════════════════════════════════════════════════════════
const APPLICATIONS_EXTRA = [
  {
    jobTitle: 'Thiết kế poster sự kiện CLB Robotics',
    applicantId: 'seed-user-001',
    applicantName: 'Nguyễn Văn An',
    applicantPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=an',
    message: 'Mình có kinh nghiệm thiết kế poster cho nhiều CLB tại BK.',
    status: 'pending',
  },
  {
    jobTitle: 'Thiết kế poster sự kiện CLB Robotics',
    applicantId: 'seed-user-006',
    applicantName: 'Nguyễn Thu Hương',
    applicantPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=huong',
    message: 'Mình học UI/UX và có kinh nghiệm thiết kế bằng Figma + Illustrator.',
    status: 'pending',
  },
  {
    jobTitle: 'Thiết kế poster sự kiện CLB Robotics',
    applicantId: 'seed-user-010',
    applicantName: 'Lê Hoàng Phúc',
    applicantPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=phuc',
    message: 'Có khả năng thiết kế poster kết hợp video teaser. Deliver trong 24h.',
    status: 'pending',
  },
  {
    jobTitle: 'Gia sư Giải tích 1 cho sinh viên năm nhất',
    applicantId: 'seed-user-005',
    applicantName: 'Hoàng Minh Đức',
    applicantPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=duc',
    message: 'Đạt A+ Giải tích 1, đã dạy kèm 3 sinh viên năm nhất.',
    status: 'pending',
  },
  {
    jobTitle: 'Gia sư Giải tích 1 cho sinh viên năm nhất',
    applicantId: 'seed-user-013',
    applicantName: 'Nguyễn Đức Huy',
    applicantPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=huy',
    message: 'GPA 3.8, đã dạy kèm hơn 20 SV Giải tích. Có tài liệu tự biên soạn.',
    status: 'pending',
  },
  {
    jobTitle: 'Dịch tài liệu kỹ thuật Anh-Việt (8 trang)',
    applicantId: 'seed-user-001',
    applicantName: 'Nguyễn Văn An',
    applicantPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=an',
    message: 'TOEIC 850, từng dịch tài liệu kỹ thuật cho dự án thực tập.',
    status: 'pending',
  },
  {
    jobTitle: 'Dịch tài liệu kỹ thuật Anh-Việt (8 trang)',
    applicantId: 'seed-user-008',
    applicantName: 'Nguyễn Thị Mai',
    applicantPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mai',
    message: 'IELTS 7.5, chuyên dịch tài liệu khoa học kỹ thuật. 10+ bài ISI.',
    status: 'pending',
  },
  {
    jobTitle: 'Phân tích dữ liệu bán hàng bằng Python',
    applicantId: 'seed-user-007',
    applicantName: 'Võ Thành Tùng',
    applicantPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=tung',
    message: 'Chuyên Data Science, thành thạo Python/Pandas/Matplotlib.',
    status: 'pending',
  },
  {
    jobTitle: 'Phân tích dữ liệu bán hàng bằng Python',
    applicantId: 'seed-user-012',
    applicantName: 'Đỗ Thùy Linh',
    applicantPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=linh',
    message: 'Đã làm nhiều project phân tích dữ liệu bằng Python.',
    status: 'pending',
  },
  {
    jobTitle: 'Thiết kế UI/UX cho app di động (Figma)',
    applicantId: 'seed-user-006',
    applicantName: 'Nguyễn Thu Hương',
    applicantPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=huong',
    message: 'Đang thực tập UI/UX, portfolio 15+ dự án Figma. Rất phù hợp!',
    status: 'pending',
  },
  {
    jobTitle: 'Tình nguyện hỗ trợ Ngày hội Tuyển sinh BK 2026',
    applicantId: 'seed-user-014',
    applicantName: 'Bùi Ngọc Hân',
    applicantPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=han',
    message: 'TNV tích cực, đã tham gia 5+ sự kiện tình nguyện tại BK.',
    status: 'pending',
  },
  {
    jobTitle: 'Tình nguyện hỗ trợ Ngày hội Tuyển sinh BK 2026',
    applicantId: 'seed-user-008',
    applicantName: 'Nguyễn Thị Mai',
    applicantPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mai',
    message: 'Muốn tham gia tình nguyện, có kinh nghiệm hướng dẫn tại open day.',
    status: 'pending',
  },
  {
    jobTitle: 'Tình nguyện hỗ trợ Ngày hội Tuyển sinh BK 2026',
    applicantId: 'seed-user-013',
    applicantName: 'Nguyễn Đức Huy',
    applicantPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=huy',
    message: 'Sẵn sàng hỗ trợ ngày tuyển sinh, giao tiếp tốt và nhiệt tình.',
    status: 'pending',
  },
  {
    jobTitle: 'Cần gấp: Sửa bug website ReactJS trước thuyết trình',
    applicantId: 'seed-user-015',
    applicantName: 'Lý Thanh Đạt',
    applicantPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=dat',
    message: 'Senior React dev, Fiverr level 2. Fix bug nhanh chóng.',
    status: 'pending',
  },
  {
    jobTitle: 'Cần gấp: Sửa bug website ReactJS trước thuyết trình',
    applicantId: 'seed-user-001',
    applicantName: 'Nguyễn Văn An',
    applicantPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=an',
    message: 'Kinh nghiệm React 2 năm, đã fix nhiều bug production.',
    status: 'pending',
  },
  {
    jobTitle: 'Cần gấp: Quay video sự kiện Hackathon tối nay',
    applicantId: 'seed-user-010',
    applicantName: 'Lê Hoàng Phúc',
    applicantPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=phuc',
    message: 'Content creator, có Sony A6400 + gimbal + mic. Sẵn sàng tối nay.',
    status: 'pending',
  },
  {
    jobTitle: 'Viết bài SEO cho blog công nghệ (5 bài)',
    applicantId: 'seed-user-005',
    applicantName: 'Hoàng Minh Đức',
    applicantPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=duc',
    message: 'Viết blog công nghệ cá nhân, có kiến thức SEO cơ bản.',
    status: 'pending',
  },
  {
    jobTitle: 'Tạo dashboard Power BI từ dữ liệu khảo sát',
    applicantId: 'seed-user-012',
    applicantName: 'Đỗ Thùy Linh',
    applicantPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=linh',
    message: 'Thành thạo Power BI, đã tạo 10+ dashboard cho các project.',
    status: 'pending',
  },
  {
    jobTitle: 'Tạo dashboard Power BI từ dữ liệu khảo sát',
    applicantId: 'seed-user-007',
    applicantName: 'Võ Thành Tùng',
    applicantPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=tung',
    message: 'Dùng Power BI và Python đều được, dashboard interactive chuyên nghiệp.',
    status: 'pending',
  },
  {
    jobTitle: 'Chụp ảnh sản phẩm cho shop online (50 sản phẩm)',
    applicantId: 'seed-user-010',
    applicantName: 'Lê Hoàng Phúc',
    applicantPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=phuc',
    message: 'Kinh nghiệm chụp ảnh sản phẩm, sở hữu studio mini tại nhà.',
    status: 'pending',
  },
  {
    jobTitle: 'Gia sư môn Xác suất Thống kê cho nhóm 3 người',
    applicantId: 'seed-user-013',
    applicantName: 'Nguyễn Đức Huy',
    applicantPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=huy',
    message: 'Đạt A+ XSTK, đã dạy kèm 10+ SV. Có tài liệu bổ sung.',
    status: 'pending',
  },
  {
    jobTitle: 'Gia sư môn Xác suất Thống kê cho nhóm 3 người',
    applicantId: 'seed-user-007',
    applicantName: 'Võ Thành Tùng',
    applicantPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=tung',
    message: 'Data Science background, XSTK là nền tảng. Dạy theo hướng ứng dụng.',
    status: 'pending',
  },
];

// ══════════════════════════════════════════════════════════════════════════════
// 4. RATINGS  (16 ratings for 6 completed jobs)
// ══════════════════════════════════════════════════════════════════════════════
const RATINGS_DATA = [
  // Slide PPT: poster(001) <-> worker(006)
  { jobTitle: 'Thiết kế slide thuyết trình đồ án tốt nghiệp', fromUserId: 'seed-user-001', toUserId: 'seed-user-006', score: 5, comment: 'Hương thiết kế rất đẹp, đúng yêu cầu, giao đúng hạn!', type: 'poster-to-worker' },
  { jobTitle: 'Thiết kế slide thuyết trình đồ án tốt nghiệp', fromUserId: 'seed-user-006', toUserId: 'seed-user-001', score: 5, comment: 'Anh An cung cấp brief rõ ràng, feedback nhanh.', type: 'worker-to-poster' },
  // Abstract dịch: poster(003) <-> worker(005)
  { jobTitle: 'Dịch abstract luận văn sang tiếng Anh', fromUserId: 'seed-user-003', toUserId: 'seed-user-005', score: 4, comment: 'Dịch chính xác, văn phong tốt, hơi chậm deadline.', type: 'poster-to-worker' },
  { jobTitle: 'Dịch abstract luận văn sang tiếng Anh', fromUserId: 'seed-user-005', toUserId: 'seed-user-003', score: 5, comment: 'Yêu cầu rõ ràng, thanh toán đúng hạn.', type: 'worker-to-poster' },
  // Portfolio HTML: poster(008) <-> worker(015)
  { jobTitle: 'Tạo website portfolio cá nhân bằng HTML/CSS', fromUserId: 'seed-user-008', toUserId: 'seed-user-015', score: 5, comment: 'Code sạch, responsive hoàn hảo, bàn giao sớm 1 ngày!', type: 'poster-to-worker' },
  { jobTitle: 'Tạo website portfolio cá nhân bằng HTML/CSS', fromUserId: 'seed-user-015', toUserId: 'seed-user-008', score: 5, comment: 'Chị Mai cung cấp content đầy đủ, feedback chi tiết.', type: 'worker-to-poster' },
  // Ansys: poster(009) <-> worker(003)
  { jobTitle: 'Chạy mô phỏng Ansys cho bài tập Cơ học kết cấu', fromUserId: 'seed-user-009', toUserId: 'seed-user-003', score: 5, comment: 'Anh Cường rất chuyên nghiệp, report chi tiết.', type: 'poster-to-worker' },
  { jobTitle: 'Chạy mô phỏng Ansys cho bài tập Cơ học kết cấu', fromUserId: 'seed-user-003', toUserId: 'seed-user-009', score: 4, comment: 'Đề bài rõ ràng nhưng deadline hơi gấp.', type: 'worker-to-poster' },
  // Data SKTT: poster(013) <-> worker(007)
  { jobTitle: 'Phân tích dữ liệu khảo sát sức khỏe tinh thần SV', fromUserId: 'seed-user-013', toUserId: 'seed-user-007', score: 5, comment: 'Tùng phân tích chuyên nghiệp, biểu đồ đẹp!', type: 'poster-to-worker' },
  { jobTitle: 'Phân tích dữ liệu khảo sát sức khỏe tinh thần SV', fromUserId: 'seed-user-007', toUserId: 'seed-user-013', score: 5, comment: 'Dataset sạch, yêu cầu cụ thể. Dễ hợp tác.', type: 'worker-to-poster' },
  // Video CLB: poster(004) <-> worker(010)
  { jobTitle: 'Quay và dựng video giới thiệu CLB Truyền thông BK', fromUserId: 'seed-user-004', toUserId: 'seed-user-010', score: 5, comment: 'Phúc quay rất đẹp, dựng phim chuyên nghiệp!', type: 'poster-to-worker' },
  { jobTitle: 'Quay và dựng video giới thiệu CLB Truyền thông BK', fromUserId: 'seed-user-010', toUserId: 'seed-user-004', score: 5, comment: 'Chị Diễm tổ chức buổi quay tốt, thanh toán nhanh.', type: 'worker-to-poster' },
  // Extra ratings (simulating history)
  { jobTitle: 'Thiết kế slide thuyết trình đồ án tốt nghiệp', fromUserId: 'seed-user-004', toUserId: 'seed-user-006', score: 4, comment: 'Hương thiết kế ổn, có sáng tạo.', type: 'poster-to-worker' },
  { jobTitle: 'Dịch abstract luận văn sang tiếng Anh', fromUserId: 'seed-user-008', toUserId: 'seed-user-005', score: 5, comment: 'Đức dịch rất giỏi, hiểu sâu thuật ngữ chuyên ngành.', type: 'poster-to-worker' },
  { jobTitle: 'Tạo website portfolio cá nhân bằng HTML/CSS', fromUserId: 'seed-user-007', toUserId: 'seed-user-015', score: 4, comment: 'Code tốt, nhưng animations hơi nhiều trên mobile.', type: 'poster-to-worker' },
  { jobTitle: 'Phân tích dữ liệu khảo sát sức khỏe tinh thần SV', fromUserId: 'seed-user-012', toUserId: 'seed-user-007', score: 5, comment: 'Tùng phân tích data rất nhanh, kết quả chính xác.', type: 'poster-to-worker' },
];

// ══════════════════════════════════════════════════════════════════════════════
// 5. WORK HISTORY  (for completed jobs)
// ══════════════════════════════════════════════════════════════════════════════
const WORK_HISTORY = [
  { user1: 'seed-user-001', user2: 'seed-user-006', jobTitle: 'Thiết kế slide thuyết trình đồ án tốt nghiệp', rating: 5 },
  { user1: 'seed-user-003', user2: 'seed-user-005', jobTitle: 'Dịch abstract luận văn sang tiếng Anh', rating: 4.5 },
  { user1: 'seed-user-008', user2: 'seed-user-015', jobTitle: 'Tạo website portfolio cá nhân bằng HTML/CSS', rating: 5 },
  { user1: 'seed-user-009', user2: 'seed-user-003', jobTitle: 'Chạy mô phỏng Ansys cho bài tập Cơ học kết cấu', rating: 4.5 },
  { user1: 'seed-user-013', user2: 'seed-user-007', jobTitle: 'Phân tích dữ liệu khảo sát sức khỏe tinh thần SV', rating: 5 },
  { user1: 'seed-user-004', user2: 'seed-user-010', jobTitle: 'Quay và dựng video giới thiệu CLB Truyền thông BK', rating: 5 },
];

// ══════════════════════════════════════════════════════════════════════════════
// SEED FUNCTIONS
// ══════════════════════════════════════════════════════════════════════════════

async function seedUsers() {
  console.log('\n--- Seeding users...');
  for (const user of USERS) {
    const now = Timestamp.now();
    await setDoc(doc(db, 'users', user.uid), { ...user, createdAt: now, updatedAt: now });
    console.log(`  + ${user.displayName} (${user.uid})`);
  }
}

async function seedJobs() {
  console.log('\n--- Seeding jobs...');
  const jobIds = {};
  for (const job of JOBS) {
    const ref = await addDoc(collection(db, 'jobs'), job);
    jobIds[job.title] = ref.id;
    const tag = job.isUrgent ? 'URGENT' : job.status.toUpperCase();
    console.log(`  + [${tag}] ${job.title}`);
  }
  return jobIds;
}

async function seedApplications(jobIds) {
  console.log('\n--- Seeding applications...');
  let count = 0;
  for (const app of APPLICATIONS_EXTRA) {
    const jobId = jobIds[app.jobTitle];
    if (!jobId) { console.warn(`  ! Job not found: ${app.jobTitle}`); continue; }
    const now = Timestamp.now();
    await addDoc(collection(db, 'applications'), {
      jobId,
      applicantId: app.applicantId,
      applicantName: app.applicantName,
      applicantPhoto: app.applicantPhoto,
      message: app.message,
      status: app.status,
      createdAt: now,
      updatedAt: now,
    });
    count++;
    console.log(`  + ${app.applicantName} -> ${app.jobTitle.substring(0, 45)}...`);
  }
  return count;
}

async function seedRatingsAndCompletions(jobIds) {
  console.log('\n--- Seeding ratings & completions...');
  const completedTitles = JOBS.filter((j) => j.status === 'completed').map((j) => j.title);

  for (const title of completedTitles) {
    const jobId = jobIds[title];
    if (!jobId) continue;
    await addDoc(collection(db, 'jobCompletions'), {
      jobId,
      workerConfirmed: true,
      posterConfirmed: true,
      completedAt: Timestamp.now(),
      status: 'confirmed',
    });
    console.log(`  + Completion: ${title.substring(0, 45)}...`);
  }

  let ratingCount = 0;
  for (const r of RATINGS_DATA) {
    const jobId = jobIds[r.jobTitle];
    if (!jobId) continue;
    await addDoc(collection(db, 'ratings'), {
      jobId,
      fromUserId: r.fromUserId,
      toUserId: r.toUserId,
      score: r.score,
      comment: r.comment,
      type: r.type,
      createdAt: Timestamp.now(),
    });
    ratingCount++;
  }
  console.log(`  + ${ratingCount} ratings created`);
  return ratingCount;
}

async function seedWorkHistory(jobIds) {
  console.log('\n--- Seeding work history...');
  let count = 0;
  for (const wh of WORK_HISTORY) {
    const jobId = jobIds[wh.jobTitle];
    if (!jobId) continue;
    await addDoc(collection(db, 'workHistory'), {
      user1: wh.user1,
      user2: wh.user2,
      jobId,
      completedAt: Timestamp.now(),
      rating: wh.rating,
    });
    count++;
  }
  console.log(`  + ${count} work history records created`);
  return count;
}

// ══════════════════════════════════════════════════════════════════════════════
// MAIN
// ══════════════════════════════════════════════════════════════════════════════
async function main() {
  console.log('=== UniJob — Firestore Seed (v3 Enhanced) ===');
  console.log(`Project: unijob-ad6eb\n`);

  const stats = {
    open: JOBS.filter((j) => j.status === 'open' && !j.isUrgent).length,
    urgent: JOBS.filter((j) => j.isUrgent).length,
    inProgress: JOBS.filter((j) => j.status === 'in-progress').length,
    completed: JOBS.filter((j) => j.status === 'completed').length,
  };

  try {
    await seedUsers();
    const jobIds = await seedJobs();
    const appCount = await seedApplications(jobIds);
    const ratingCount = await seedRatingsAndCompletions(jobIds);
    const whCount = await seedWorkHistory(jobIds);

    console.log('\n=== Seed complete! ===');
    console.log(`   Users          : ${USERS.length}`);
    console.log(`   Jobs (total)   : ${JOBS.length}`);
    console.log(`     - Open       : ${stats.open}`);
    console.log(`     - Urgent     : ${stats.urgent}`);
    console.log(`     - In-progress: ${stats.inProgress}`);
    console.log(`     - Completed  : ${stats.completed}`);
    console.log(`   Applications   : ${appCount}`);
    console.log(`   Ratings        : ${ratingCount}`);
    console.log(`   Completions    : ${stats.completed}`);
    console.log(`   Work History   : ${whCount}`);
    console.log('\n-> Open Firebase Console -> Firestore to verify.');
  } catch (err) {
    console.error('\n!!! Seed failed:', err.message);
    console.error(err);
  } finally {
    process.exit(0);
  }
}

main();
